import { useState } from 'react';
import useCapturasCompraRapida from '../hooks/useCapturasCompraRapida';
import { formatDateTime } from '../utils/solicitudesCompraUtils';
import { formatFileSize, MAX_INVOICE_EVIDENCES } from '../utils/solicitudesCompraRecepcionUtils';

export default function CapturasCompraRapidaOperativa({ onBack, openToast }) {
  const flow = useCapturasCompraRapida({ openToast });
  const [discardOpen, setDiscardOpen] = useState(false);
  const draftState = String(flow.draft?.estado || 'BORRADOR').toUpperCase();
  const editable = draftState === 'BORRADOR';
  if (flow.mode === 'list') return (
    <section className="sol-comp-section sol-comp-quick-capture">
      <header className="sol-comp-header"><div><h2>Mis capturas rápidas</h2><p>Consulta borradores y facturas enviadas a Administración.</p></div><div className="sol-comp-header-actions"><button className="btn btn-outline-secondary" type="button" onClick={onBack}>Volver</button><button className="btn btn-primary" type="button" onClick={flow.openNew}><i className="bi bi-camera" /> Nueva captura</button></div></header>
      {flow.list.loading ? <div className="sol-comp-feedback">Cargando capturas…</div> : null}
      {flow.list.error ? <div className="sol-comp-feedback sol-comp-feedback--error">{flow.list.error}</div> : null}
      <div className="sol-comp-list">
        {flow.list.items.map((item) => <article className="sol-comp-request-card" key={item.id_captura_compra_rapida}><div className="sol-comp-card-top"><strong>Captura rápida #{item.id_captura_compra_rapida}</strong><span className={`sol-comp-state sol-comp-state--${String(item.estado).toLowerCase()}`}>{item.estado}</span></div><div className="sol-comp-meta-grid"><span><small>Fecha</small>{formatDateTime(item.fecha_creacion)}</span><span><small>Facturas</small>{item.cantidad_evidencias || 0}</span><span><small>Sucursal</small>{item.sucursal?.nombre || '—'}</span><span><small>Almacén</small>{item.almacen?.nombre || '—'}</span></div><button type="button" className="btn btn-outline-primary btn-sm" onClick={() => flow.loadCapture(item.id_captura_compra_rapida)}>{item.estado === 'BORRADOR' ? 'Continuar captura' : 'Ver estado'} <i className="bi bi-arrow-right" aria-hidden="true" /></button></article>)}
      </div>
    </section>
  );
  return (
    <section className="sol-comp-section sol-comp-quick-capture">
      <header className="sol-comp-header"><div><h2>Compra rápida</h2><p>Sube la factura y envíala a Administración.</p></div><button type="button" className="btn btn-outline-secondary" disabled={flow.busy === 'upload'} onClick={() => flow.setMode('list')}>Volver</button></header>
      <ol className="sol-comp-quick-steps" aria-label="Progreso de compra rápida"><li className={editable ? 'is-active' : 'is-complete'}><b>1</b><span>Factura</span></li><li className={draftState === 'BORRADOR' ? 'is-active' : 'is-complete'}><b>2</b><span>Enviar</span></li><li className={draftState !== 'BORRADOR' ? 'is-active' : ''}><b>3</b><span>Administración</span></li></ol>
      {flow.draft ? <div className="sol-comp-warehouse"><strong>{draftState} #{flow.draft.id_captura_compra_rapida}</strong><span>{flow.draft.sucursal?.nombre || ''} {flow.draft.almacen?.nombre || ''}</span></div> : null}
      <div className="sol-comp-reception-panel" aria-busy={flow.busy === 'upload'}>
        <h3>Factura / comprobantes</h3>
        {editable ? <div className="sol-comp-header-actions"><label className={`btn btn-outline-primary${flow.busy === 'upload' ? ' disabled' : ''}`} htmlFor="quick-camera" aria-disabled={flow.busy === 'upload'}><i className="bi bi-camera" /> Tomar foto</label><input id="quick-camera" hidden disabled={flow.busy === 'upload'} type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={(event) => { const files = Array.from(event.currentTarget.files || []); event.currentTarget.value = ''; void flow.addFiles(files); }} /><label className={`btn btn-outline-secondary${flow.busy === 'upload' ? ' disabled' : ''}`} htmlFor="quick-files" aria-disabled={flow.busy === 'upload'}><i className="bi bi-images" /> Seleccionar imágenes</label><input id="quick-files" hidden disabled={flow.busy === 'upload'} type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(event) => { const files = Array.from(event.currentTarget.files || []); event.currentTarget.value = ''; void flow.addFiles(files); }} /></div> : null}
        <p>{flow.evidence.length + flow.temporaryEvidence.length} de {MAX_INVOICE_EVIDENCES} imágenes</p>
        {flow.busy === 'upload' ? <div className="sol-comp-upload-progress" aria-live="polite"><strong>Subiendo imágenes…</strong><span>{flow.uploadProgress.completed} de {flow.uploadProgress.total} completadas</span>{flow.uploadProgress.currentFile ? <small>{flow.uploadProgress.currentFile}</small> : null}</div> : null}
        {draftState === 'RECHAZADA' && flow.draft?.motivo_rechazo ? <div className="sol-comp-feedback sol-comp-feedback--error"><strong>Motivo del rechazo</strong><span>{flow.draft.motivo_rechazo}</span></div> : null}
        {draftState === 'FORMALIZADA' && flow.draft?.id_solicitud_compra ? <div className="sol-comp-feedback"><strong>Orden generada:</strong> #{flow.draft.id_solicitud_compra}</div> : null}
        {flow.error ? <div className="sol-comp-feedback sol-comp-feedback--error">{flow.error}</div> : null}
        <div className="sol-comp-invoice-grid">{flow.temporaryEvidence.map((item) => <article className={`sol-comp-invoice-preview sol-comp-invoice-preview--${item.estado.toLowerCase()}`} key={item.id_temporal}><img src={item.previewUrl} alt={item.nombre_original || 'Factura pendiente'} /><div><strong>{item.nombre_original}</strong><small>{formatFileSize(item.tamano_bytes)}</small><span className="sol-comp-upload-state">{item.estado}</span></div>{editable && flow.busy !== 'upload' ? <button className="btn btn-outline-danger btn-sm" type="button" onClick={() => flow.removeTemporaryEvidence(item.id_temporal)} aria-label={`Quitar ${item.nombre_original || 'factura temporal'}`}>×</button> : null}</article>)}{flow.evidence.map((item) => <article className="sol-comp-invoice-preview" key={item.id_evidencia}>{item.url_firmada ? <img src={item.url_firmada} alt={item.nombre_original || 'Factura'} /> : null}<div><strong>{item.nombre_original || 'Factura'}</strong><small>{item.tamano_bytes ? formatFileSize(item.tamano_bytes) : item.mime_type}</small><span className="sol-comp-upload-state">GUARDADA</span></div>{editable ? <button className="btn btn-outline-danger btn-sm" disabled={Boolean(flow.busy)} type="button" onClick={() => flow.removeEvidence(item.id_evidencia)} aria-label={`Quitar ${item.nombre_original || 'factura'}`}>×</button> : null}</article>)}</div>
        {editable ? <div className="sol-comp-quick-send"><p>Las facturas quedarán en solo lectura después del envío.</p><div className="sol-comp-review-actions"><button type="button" className="btn btn-outline-danger" disabled={!flow.draft || Boolean(flow.busy)} onClick={() => setDiscardOpen(true)}>Descartar borrador</button><button type="button" className="btn btn-primary" disabled={!flow.draft || flow.evidence.length < 1 || Boolean(flow.busy)} onClick={flow.send}>{flow.busy === 'send' ? 'Enviando…' : 'Enviar a Administración'}</button></div></div> : <p className="sol-comp-feedback">Las fotografías están en modo de solo lectura.</p>}
      </div>
      {discardOpen ? <div className="sol-comp-modal-backdrop" role="presentation"><div className="sol-comp-modal" role="dialog" aria-modal="true" aria-labelledby="discard-capture-title"><h3 id="discard-capture-title">Descartar captura</h3><p>Se eliminará este borrador y sus imágenes todavía no enviadas.</p><div className="sol-comp-review-actions"><button type="button" className="btn btn-outline-secondary" disabled={Boolean(flow.busy)} onClick={() => setDiscardOpen(false)}>Volver</button><button type="button" className="btn btn-danger" disabled={Boolean(flow.busy)} onClick={async () => { await flow.discard(); setDiscardOpen(false); }}>Descartar borrador</button></div></div></div> : null}
    </section>
  );
}
