const uniquePermissions = (values) => {
  const seen = new Set();
  const result = [];

  (Array.isArray(values) ? values : []).forEach((value) => {
    const normalized = String(value ?? '').trim().toUpperCase();
    if (!normalized || seen.has(normalized)) return;
    seen.add(normalized);
    result.push(normalized);
  });

  return result;
};

const PERMISSION_VALUES = Object.freeze({
  DASHBOARD_VER: 'DASHBOARD_VER',
  PERFIL_VER: 'PERFIL_VER',
  PERFIL_EDITAR: 'PERFIL_EDITAR',
  PERFIL_PASSWORD_CAMBIAR: 'PERFIL_PASSWORD_CAMBIAR',

  PERSONAS_MODULO_VER: 'PERSONAS_MODULO_VER',
  PERSONAS_VER: 'PERSONAS_VER',
  PERSONAS_CREAR: 'PERSONAS_CREAR',
  PERSONAS_EDITAR: 'PERSONAS_EDITAR',
  PERSONAS_ELIMINAR: 'PERSONAS_ELIMINAR',
  EMPRESAS_VER: 'EMPRESAS_VER',
  EMPRESAS_CREAR: 'EMPRESAS_CREAR',
  EMPRESAS_EDITAR: 'EMPRESAS_EDITAR',
  EMPRESAS_ELIMINAR: 'EMPRESAS_ELIMINAR',
  EMPRESAS_ESTADO_CAMBIAR: 'EMPRESAS_ESTADO_CAMBIAR',
  CLIENTES_VER: 'CLIENTES_VER',
  CLIENTES_CREAR: 'CLIENTES_CREAR',
  CLIENTES_EDITAR: 'CLIENTES_EDITAR',
  CLIENTES_ELIMINAR: 'CLIENTES_ELIMINAR',
  EMPLEADOS_VER: 'EMPLEADOS_VER',
  EMPLEADOS_CREAR: 'EMPLEADOS_CREAR',
  EMPLEADOS_EDITAR: 'EMPLEADOS_EDITAR',
  EMPLEADOS_ELIMINAR: 'EMPLEADOS_ELIMINAR',
  EMPLEADOS_DETALLE_VER: 'EMPLEADOS_DETALLE_VER',
  USUARIOS_VER: 'USUARIOS_VER',
  USUARIOS_CREAR: 'USUARIOS_CREAR',
  USUARIOS_EDITAR: 'USUARIOS_EDITAR',
  USUARIOS_ELIMINAR: 'USUARIOS_ELIMINAR',
  USUARIOS_DETALLE_VER: 'USUARIOS_DETALLE_VER',
  USUARIOS_PASSWORD_RESETEAR: 'USUARIOS_PASSWORD_RESETEAR',
  USUARIOS_IMAGEN_SUBIR: 'USUARIOS_IMAGEN_SUBIR',
  USUARIOS_IMAGEN_ELIMINAR: 'USUARIOS_IMAGEN_ELIMINAR',
  ROLES_PERMISOS_VER: 'ROLES_PERMISOS_VER',
  ROLES_PERMISOS_DETALLE_VER: 'ROLES_PERMISOS_DETALLE_VER',
  ROLES_PERMISOS_EDITAR: 'ROLES_PERMISOS_EDITAR',

  SUCURSALES_VER: 'SUCURSALES_VER',
  SUCURSALES_CREAR: 'SUCURSALES_CREAR',
  SUCURSALES_EDITAR: 'SUCURSALES_EDITAR',
  SUCURSALES_ELIMINAR: 'SUCURSALES_ELIMINAR',
  SUCURSALES_ESTADO_CAMBIAR: 'SUCURSALES_ESTADO_CAMBIAR',

  INVENTARIO_VER: 'INVENTARIO_VER',
  INVENTARIO_CATEGORIAS_VER: 'INVENTARIO_CATEGORIAS_VER',
  INVENTARIO_CATEGORIAS_CREAR: 'INVENTARIO_CATEGORIAS_CREAR',
  INVENTARIO_CATEGORIAS_EDITAR: 'INVENTARIO_CATEGORIAS_EDITAR',
  INVENTARIO_CATEGORIAS_ELIMINAR: 'INVENTARIO_CATEGORIAS_ELIMINAR',
  INVENTARIO_CATEGORIAS_ESTADO_CAMBIAR: 'INVENTARIO_CATEGORIAS_ESTADO_CAMBIAR',
  INVENTARIO_CATEGORIAS_INSUMOS_VER: 'INVENTARIO_CATEGORIAS_INSUMOS_VER',
  INVENTARIO_CATEGORIAS_INSUMOS_CREAR: 'INVENTARIO_CATEGORIAS_INSUMOS_CREAR',
  INVENTARIO_CATEGORIAS_INSUMOS_EDITAR: 'INVENTARIO_CATEGORIAS_INSUMOS_EDITAR',
  INVENTARIO_CATEGORIAS_INSUMOS_ELIMINAR: 'INVENTARIO_CATEGORIAS_INSUMOS_ELIMINAR',
  INVENTARIO_CATEGORIAS_INSUMOS_ESTADO_CAMBIAR: 'INVENTARIO_CATEGORIAS_INSUMOS_ESTADO_CAMBIAR',
  INVENTARIO_INSUMOS_VER: 'INVENTARIO_INSUMOS_VER',
  INVENTARIO_INSUMOS_CREAR: 'INVENTARIO_INSUMOS_CREAR',
  INVENTARIO_INSUMOS_EDITAR: 'INVENTARIO_INSUMOS_EDITAR',
  INVENTARIO_INSUMOS_ELIMINAR: 'INVENTARIO_INSUMOS_ELIMINAR',
  INVENTARIO_INSUMOS_ESTADO_CAMBIAR: 'INVENTARIO_INSUMOS_ESTADO_CAMBIAR',
  INVENTARIO_PRODUCTOS_VER: 'INVENTARIO_PRODUCTOS_VER',
  INVENTARIO_PRODUCTOS_CREAR: 'INVENTARIO_PRODUCTOS_CREAR',
  INVENTARIO_PRODUCTOS_EDITAR: 'INVENTARIO_PRODUCTOS_EDITAR',
  INVENTARIO_PRODUCTOS_ELIMINAR: 'INVENTARIO_PRODUCTOS_ELIMINAR',
  INVENTARIO_PRODUCTOS_DETALLE_VER: 'INVENTARIO_PRODUCTOS_DETALLE_VER',
  INVENTARIO_PRODUCTOS_ESTADO_CAMBIAR: 'INVENTARIO_PRODUCTOS_ESTADO_CAMBIAR',
  INVENTARIO_PRODUCTOS_IMAGEN_SUBIR: 'INVENTARIO_PRODUCTOS_IMAGEN_SUBIR',
  INVENTARIO_PRODUCTOS_IMAGEN_ELIMINAR: 'INVENTARIO_PRODUCTOS_IMAGEN_ELIMINAR',
  INVENTARIO_ALMACENES_VER: 'INVENTARIO_ALMACENES_VER',
  INVENTARIO_ALMACENES_CREAR: 'INVENTARIO_ALMACENES_CREAR',
  INVENTARIO_ALMACENES_EDITAR: 'INVENTARIO_ALMACENES_EDITAR',
  INVENTARIO_ALMACENES_ELIMINAR: 'INVENTARIO_ALMACENES_ELIMINAR',
  INVENTARIO_MOVIMIENTOS_VER: 'INVENTARIO_MOVIMIENTOS_VER',
  INVENTARIO_MOVIMIENTOS_CREAR: 'INVENTARIO_MOVIMIENTOS_CREAR',
  INVENTARIO_MOVIMIENTOS_EDITAR: 'INVENTARIO_MOVIMIENTOS_EDITAR',
  INVENTARIO_MOVIMIENTOS_ELIMINAR: 'INVENTARIO_MOVIMIENTOS_ELIMINAR',
  INVENTARIO_ALERTAS_VER: 'INVENTARIO_ALERTAS_VER',
  INVENTARIO_ALERTAS_ACTUALIZAR: 'INVENTARIO_ALERTAS_ACTUALIZAR',
  INVENTARIO_ALERTAS_STOCK_MINIMO_EDITAR: 'INVENTARIO_ALERTAS_STOCK_MINIMO_EDITAR',

  VENTAS_VER: 'VENTAS_VER',
  VENTAS_CREAR: 'VENTAS_CREAR',
  VENTAS_EXPORTAR: 'VENTAS_EXPORTAR',
  VENTAS_IMPRIMIR: 'VENTAS_IMPRIMIR',
  VENTAS_DETALLE_VER: 'VENTAS_DETALLE_VER',
  VENTAS_CARRITO_EDITAR: 'VENTAS_CARRITO_EDITAR',
  VENTAS_DESCUENTO_APLICAR: 'VENTAS_DESCUENTO_APLICAR',
  VENTAS_METODO_PAGO_SELECCIONAR: 'VENTAS_METODO_PAGO_SELECCIONAR',

  COCINA_VER: 'COCINA_VER',
  COCINA_ACTUALIZAR_TABLERO: 'COCINA_ACTUALIZAR_TABLERO',
  COCINA_BUSCAR: 'COCINA_BUSCAR',
  COCINA_DETALLE_VER: 'COCINA_DETALLE_VER',
  COCINA_FILTRAR_SUCURSAL: 'COCINA_FILTRAR_SUCURSAL',
  COCINA_PEDIDO_INICIAR: 'COCINA_PEDIDO_INICIAR',
  COCINA_PEDIDO_MARCAR_LISTO: 'COCINA_PEDIDO_MARCAR_LISTO',
  COCINA_PEDIDO_ENTREGAR: 'COCINA_PEDIDO_ENTREGAR',

  MENU_VER: 'MENU_VER',
  MENU_PEDIDO_AGREGAR_ITEM: 'MENU_PEDIDO_AGREGAR_ITEM',
  MENU_PRODUCTO_DETALLE_VER: 'MENU_PRODUCTO_DETALLE_VER',
  MENU_PEDIDO_EDITAR_CANTIDAD: 'MENU_PEDIDO_EDITAR_CANTIDAD',
  MENU_PEDIDO_ELIMINAR_ITEM: 'MENU_PEDIDO_ELIMINAR_ITEM',
  MENU_PEDIDO_CONFIRMAR: 'MENU_PEDIDO_CONFIRMAR',

  SEGURIDAD_VER: 'SEGURIDAD_VER',
  SEGURIDAD_CONFIG_VER: 'SEGURIDAD_CONFIG_VER',
  SEGURIDAD_CONFIG_EDITAR: 'SEGURIDAD_CONFIG_EDITAR',
  SEGURIDAD_SESIONES_VER: 'SEGURIDAD_SESIONES_VER',
  SEGURIDAD_SESIONES_VER_GLOBAL: 'SEGURIDAD_SESIONES_VER_GLOBAL',
  SEGURIDAD_SESIONES_CERRAR: 'SEGURIDAD_SESIONES_CERRAR',
  SEGURIDAD_SESIONES_CERRAR_OTRAS: 'SEGURIDAD_SESIONES_CERRAR_OTRAS',
  SEGURIDAD_SESIONES_CERRAR_GLOBAL: 'SEGURIDAD_SESIONES_CERRAR_GLOBAL',
  SEGURIDAD_SESIONES_CERRAR_GLOBAL_MENOS_ACTUAL: 'SEGURIDAD_SESIONES_CERRAR_GLOBAL_MENOS_ACTUAL',
  SEGURIDAD_USUARIOS_VER: 'SEGURIDAD_USUARIOS_VER',
  SEGURIDAD_USUARIOS_AUDITORIA_VER: 'SEGURIDAD_USUARIOS_AUDITORIA_VER',
  SEGURIDAD_USUARIOS_AUDITORIA_SESIONES_VER: 'SEGURIDAD_USUARIOS_AUDITORIA_SESIONES_VER',
  SEGURIDAD_USUARIOS_AUDITORIA_LOGINS_VER: 'SEGURIDAD_USUARIOS_AUDITORIA_LOGINS_VER',
  SEGURIDAD_USUARIOS_SESIONES_CERRAR: 'SEGURIDAD_USUARIOS_SESIONES_CERRAR',
  SEGURIDAD_LOGINS_VER: 'SEGURIDAD_LOGINS_VER',

  PARAMETROS_VER: 'PARAMETROS_VER',
  PARAMETROS_CATALOGOS_VER: 'PARAMETROS_CATALOGOS_VER',
  PARAMETROS_CATALOGOS_CREAR: 'PARAMETROS_CATALOGOS_CREAR',
  PARAMETROS_CATALOGOS_EDITAR: 'PARAMETROS_CATALOGOS_EDITAR',
  PARAMETROS_CATALOGOS_ELIMINAR: 'PARAMETROS_CATALOGOS_ELIMINAR',
  PARAMETROS_CATALOGOS_RECARGAR: 'PARAMETROS_CATALOGOS_RECARGAR',
  PARAMETROS_TIPO_DEPARTAMENTO_VER: 'PARAMETROS_TIPO_DEPARTAMENTO_VER',
  PARAMETROS_CATEGORIAS_PRODUCTOS_VER: 'PARAMETROS_CATEGORIAS_PRODUCTOS_VER',
  PARAMETROS_UNIDADES_MEDIDA_VER: 'PARAMETROS_UNIDADES_MEDIDA_VER',
  PARAMETROS_TIPO_CLIENTE_VER: 'PARAMETROS_TIPO_CLIENTE_VER',
  PARAMETROS_TIPO_NOTIFICACION_VER: 'PARAMETROS_TIPO_NOTIFICACION_VER',
  PARAMETROS_ESTADOS_PEDIDO_VER: 'PARAMETROS_ESTADOS_PEDIDO_VER',
  PARAMETROS_DISPOSITIVOS_BIOMETRICOS_VER: 'PARAMETROS_DISPOSITIVOS_BIOMETRICOS_VER',
  PARAMETROS_TIPO_HORA_EXTRA_VER: 'PARAMETROS_TIPO_HORA_EXTRA_VER',
  PARAMETROS_FACTOR_HORAS_EXTRA_VER: 'PARAMETROS_FACTOR_HORAS_EXTRA_VER',
  PARAMETROS_TIPO_NOMINA_VER: 'PARAMETROS_TIPO_NOMINA_VER',
  PARAMETROS_TIPO_NATURALEZA_VER: 'PARAMETROS_TIPO_NATURALEZA_VER',
  PARAMETROS_CONCEPTO_NOMINA_VER: 'PARAMETROS_CONCEPTO_NOMINA_VER',
  PARAMETROS_ESTADO_PLANILLA_VER: 'PARAMETROS_ESTADO_PLANILLA_VER',

  CONFIGURACION_VER: 'CONFIGURACION_VER'
});

export const PERMISSIONS = Object.freeze({
  ...PERMISSION_VALUES,
  CATEGORIAS_VER: PERMISSION_VALUES.INVENTARIO_CATEGORIAS_VER,
  INSUMOS_VER: PERMISSION_VALUES.INVENTARIO_INSUMOS_VER,
  PRODUCTOS_VER: PERMISSION_VALUES.INVENTARIO_PRODUCTOS_VER,
  ALMACENES_VER: PERMISSION_VALUES.INVENTARIO_ALMACENES_VER,
  MOVIMIENTOS_VER: PERMISSION_VALUES.INVENTARIO_MOVIMIENTOS_VER,
  ALERTAS_VER: PERMISSION_VALUES.INVENTARIO_ALERTAS_VER,
  ALERTAS_STOCK_MINIMO_EDITAR: PERMISSION_VALUES.INVENTARIO_ALERTAS_STOCK_MINIMO_EDITAR,
  MENU_DETALLE_VER: PERMISSION_VALUES.MENU_PRODUCTO_DETALLE_VER,
  MENU_PRODUCTO_AGREGAR: PERMISSION_VALUES.MENU_PEDIDO_AGREGAR_ITEM,
  MENU_PEDIDO_EDITAR: PERMISSION_VALUES.MENU_PEDIDO_EDITAR_CANTIDAD,
  PARAMETROS_CATALOGO_VER: PERMISSION_VALUES.PARAMETROS_CATALOGOS_VER,
  PARAMETROS_CATALOGO_CREAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_CREAR,
  PARAMETROS_CATALOGO_EDITAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_EDITAR,
  PARAMETROS_CATALOGO_ELIMINAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_ELIMINAR,
  PARAMETROS_CATALOGO_RECARGAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_RECARGAR,
  SEGURIDAD_LOGS_VER: PERMISSION_VALUES.SEGURIDAD_LOGINS_VER,
  COCINA_REFRESCAR: PERMISSION_VALUES.COCINA_ACTUALIZAR_TABLERO,
  COCINA_ESTADO_CAMBIAR: PERMISSION_VALUES.COCINA_PEDIDO_MARCAR_LISTO,
  USUARIOS_FOTO_EDITAR: PERMISSION_VALUES.USUARIOS_IMAGEN_SUBIR
});

const PERMISSION_ALIASES = Object.freeze({
  CATEGORIAS_VER: PERMISSION_VALUES.INVENTARIO_CATEGORIAS_VER,
  INSUMOS_VER: PERMISSION_VALUES.INVENTARIO_INSUMOS_VER,
  PRODUCTOS_VER: PERMISSION_VALUES.INVENTARIO_PRODUCTOS_VER,
  ALMACENES_VER: PERMISSION_VALUES.INVENTARIO_ALMACENES_VER,
  MOVIMIENTOS_VER: PERMISSION_VALUES.INVENTARIO_MOVIMIENTOS_VER,
  ALERTAS_VER: PERMISSION_VALUES.INVENTARIO_ALERTAS_VER,
  ALERTAS_STOCK_MINIMO_EDITAR: PERMISSION_VALUES.INVENTARIO_ALERTAS_STOCK_MINIMO_EDITAR,
  MENU_DETALLE_VER: PERMISSION_VALUES.MENU_PRODUCTO_DETALLE_VER,
  MENU_PRODUCTO_AGREGAR: PERMISSION_VALUES.MENU_PEDIDO_AGREGAR_ITEM,
  MENU_PEDIDO_EDITAR: PERMISSION_VALUES.MENU_PEDIDO_EDITAR_CANTIDAD,
  PARAMETROS_CATALOGO_VER: PERMISSION_VALUES.PARAMETROS_CATALOGOS_VER,
  PARAMETROS_CATALOGO_CREAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_CREAR,
  PARAMETROS_CATALOGO_EDITAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_EDITAR,
  PARAMETROS_CATALOGO_ELIMINAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_ELIMINAR,
  PARAMETROS_CATALOGO_RECARGAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_RECARGAR,
  SEGURIDAD_LOGS_VER: PERMISSION_VALUES.SEGURIDAD_LOGINS_VER,
  COCINA_REFRESCAR: PERMISSION_VALUES.COCINA_ACTUALIZAR_TABLERO,
  COCINA_ESTADO_CAMBIAR: PERMISSION_VALUES.COCINA_PEDIDO_MARCAR_LISTO,
  USUARIOS_FOTO_EDITAR: PERMISSION_VALUES.USUARIOS_IMAGEN_SUBIR
});

const normalizePermission = (permiso) => {
  const normalized = String(permiso ?? '').trim().toUpperCase();
  if (!normalized) return '';
  return PERMISSION_ALIASES[normalized] || normalized;
};

export const normalizePermissions = (permisos) =>
  uniquePermissions((Array.isArray(permisos) ? permisos : []).map(normalizePermission));

export const buildPermissionSet = (permisos) => new Set(normalizePermissions(permisos));

export const normalizeRoleName = (rol) =>
  String(rol ?? '')
    .trim()
    .replace(/[\s-]+/g, '_')
    .toUpperCase();

export const normalizeRoles = (roles) =>
  uniquePermissions((Array.isArray(roles) ? roles : []).map(normalizeRoleName));

export const isSuperAdminRole = (rol) => normalizeRoleName(rol) === 'SUPER_ADMIN';

export const isSuperAdminRoleList = (roles) => normalizeRoles(roles).some(isSuperAdminRole);

export const hasPermission = (permissionSet, permiso, options = {}) => {
  if (options?.isSuperAdmin) return true;

  const normalized = normalizePermission(permiso);
  if (!normalized) return false;
  if (!(permissionSet instanceof Set)) return false;
  return permissionSet.has(normalized);
};

export const hasAnyPermission = (permissionSet, permisosRequeridos, options = {}) => {
  if (options?.isSuperAdmin) return true;
  const required = normalizePermissions(permisosRequeridos);
  if (required.length === 0) return true;
  return required.some((permiso) => hasPermission(permissionSet, permiso));
};

export const hasAllPermissions = (permissionSet, permisosRequeridos, options = {}) => {
  if (options?.isSuperAdmin) return true;
  const required = normalizePermissions(permisosRequeridos);
  if (required.length === 0) return true;
  return required.every((permiso) => hasPermission(permissionSet, permiso));
};

const INVENTARIO_TAB_PERMISSIONS_MAP = Object.freeze({
  categorias: uniquePermissions([
    PERMISSIONS.INVENTARIO_CATEGORIAS_VER,
    PERMISSIONS.INVENTARIO_CATEGORIAS_CREAR,
    PERMISSIONS.INVENTARIO_CATEGORIAS_EDITAR,
    PERMISSIONS.INVENTARIO_CATEGORIAS_ELIMINAR,
    PERMISSIONS.INVENTARIO_CATEGORIAS_ESTADO_CAMBIAR,
    PERMISSIONS.INVENTARIO_CATEGORIAS_INSUMOS_VER,
    PERMISSIONS.INVENTARIO_CATEGORIAS_INSUMOS_CREAR,
    PERMISSIONS.INVENTARIO_CATEGORIAS_INSUMOS_EDITAR,
    PERMISSIONS.INVENTARIO_CATEGORIAS_INSUMOS_ELIMINAR,
    PERMISSIONS.INVENTARIO_CATEGORIAS_INSUMOS_ESTADO_CAMBIAR
  ]),
  insumos: uniquePermissions([
    PERMISSIONS.INVENTARIO_INSUMOS_VER,
    PERMISSIONS.INVENTARIO_INSUMOS_CREAR,
    PERMISSIONS.INVENTARIO_INSUMOS_EDITAR,
    PERMISSIONS.INVENTARIO_INSUMOS_ELIMINAR,
    PERMISSIONS.INVENTARIO_INSUMOS_ESTADO_CAMBIAR
  ]),
  productos: uniquePermissions([
    PERMISSIONS.INVENTARIO_PRODUCTOS_VER,
    PERMISSIONS.INVENTARIO_PRODUCTOS_CREAR,
    PERMISSIONS.INVENTARIO_PRODUCTOS_EDITAR,
    PERMISSIONS.INVENTARIO_PRODUCTOS_ELIMINAR,
    PERMISSIONS.INVENTARIO_PRODUCTOS_DETALLE_VER,
    PERMISSIONS.INVENTARIO_PRODUCTOS_ESTADO_CAMBIAR,
    PERMISSIONS.INVENTARIO_PRODUCTOS_IMAGEN_SUBIR,
    PERMISSIONS.INVENTARIO_PRODUCTOS_IMAGEN_ELIMINAR
  ]),
  almacenes: uniquePermissions([
    PERMISSIONS.INVENTARIO_ALMACENES_VER,
    PERMISSIONS.INVENTARIO_ALMACENES_CREAR,
    PERMISSIONS.INVENTARIO_ALMACENES_EDITAR,
    PERMISSIONS.INVENTARIO_ALMACENES_ELIMINAR,
    PERMISSIONS.INVENTARIO_MOVIMIENTOS_VER,
    PERMISSIONS.INVENTARIO_MOVIMIENTOS_CREAR,
    PERMISSIONS.INVENTARIO_MOVIMIENTOS_EDITAR,
    PERMISSIONS.INVENTARIO_MOVIMIENTOS_ELIMINAR
  ]),
  alertas: uniquePermissions([
    PERMISSIONS.INVENTARIO_ALERTAS_VER,
    PERMISSIONS.INVENTARIO_ALERTAS_ACTUALIZAR,
    PERMISSIONS.INVENTARIO_ALERTAS_STOCK_MINIMO_EDITAR
  ])
});

const PERSONAS_TAB_PERMISSIONS_MAP = Object.freeze({
  personas: uniquePermissions([
    PERMISSIONS.PERSONAS_MODULO_VER,
    PERMISSIONS.PERSONAS_VER,
    PERMISSIONS.PERSONAS_CREAR,
    PERMISSIONS.PERSONAS_EDITAR,
    PERMISSIONS.PERSONAS_ELIMINAR
  ]),
  empresas: uniquePermissions([
    PERMISSIONS.EMPRESAS_VER,
    PERMISSIONS.EMPRESAS_CREAR,
    PERMISSIONS.EMPRESAS_EDITAR,
    PERMISSIONS.EMPRESAS_ELIMINAR,
    PERMISSIONS.EMPRESAS_ESTADO_CAMBIAR
  ]),
  clientes: uniquePermissions([
    PERMISSIONS.CLIENTES_VER,
    PERMISSIONS.CLIENTES_CREAR,
    PERMISSIONS.CLIENTES_EDITAR,
    PERMISSIONS.CLIENTES_ELIMINAR
  ]),
  empleados: uniquePermissions([
    PERMISSIONS.EMPLEADOS_VER,
    PERMISSIONS.EMPLEADOS_CREAR,
    PERMISSIONS.EMPLEADOS_EDITAR,
    PERMISSIONS.EMPLEADOS_ELIMINAR,
    PERMISSIONS.EMPLEADOS_DETALLE_VER
  ]),
  usuarios: uniquePermissions([
    PERMISSIONS.USUARIOS_VER,
    PERMISSIONS.USUARIOS_CREAR,
    PERMISSIONS.USUARIOS_EDITAR,
    PERMISSIONS.USUARIOS_ELIMINAR,
    PERMISSIONS.USUARIOS_DETALLE_VER,
    PERMISSIONS.USUARIOS_PASSWORD_RESETEAR,
    PERMISSIONS.USUARIOS_IMAGEN_SUBIR,
    PERMISSIONS.USUARIOS_IMAGEN_ELIMINAR
  ]),
  roles: uniquePermissions([
    PERMISSIONS.ROLES_PERMISOS_VER,
    PERMISSIONS.ROLES_PERMISOS_DETALLE_VER,
    PERMISSIONS.ROLES_PERMISOS_EDITAR
  ])
});

const SEGURIDAD_TAB_PERMISSIONS_MAP = Object.freeze({
  sesiones: uniquePermissions([
    PERMISSIONS.SEGURIDAD_VER,
    PERMISSIONS.SEGURIDAD_SESIONES_VER,
    PERMISSIONS.SEGURIDAD_SESIONES_VER_GLOBAL,
    PERMISSIONS.SEGURIDAD_SESIONES_CERRAR,
    PERMISSIONS.SEGURIDAD_SESIONES_CERRAR_OTRAS,
    PERMISSIONS.SEGURIDAD_SESIONES_CERRAR_GLOBAL,
    PERMISSIONS.SEGURIDAD_SESIONES_CERRAR_GLOBAL_MENOS_ACTUAL
  ]),
  usuarios: uniquePermissions([
    PERMISSIONS.SEGURIDAD_USUARIOS_VER,
    PERMISSIONS.SEGURIDAD_USUARIOS_AUDITORIA_VER,
    PERMISSIONS.SEGURIDAD_USUARIOS_AUDITORIA_SESIONES_VER,
    PERMISSIONS.SEGURIDAD_USUARIOS_AUDITORIA_LOGINS_VER,
    PERMISSIONS.SEGURIDAD_USUARIOS_SESIONES_CERRAR
  ]),
  password: uniquePermissions([
    PERMISSIONS.SEGURIDAD_VER,
    PERMISSIONS.SEGURIDAD_CONFIG_VER,
    PERMISSIONS.SEGURIDAD_CONFIG_EDITAR
  ]),
  logins: uniquePermissions([
    PERMISSIONS.SEGURIDAD_VER,
    PERMISSIONS.SEGURIDAD_LOGINS_VER
  ])
});

const VENTAS_TAB_PERMISSIONS_MAP = Object.freeze({
  ventas: uniquePermissions([
    PERMISSIONS.VENTAS_VER,
    PERMISSIONS.VENTAS_DETALLE_VER,
    PERMISSIONS.VENTAS_EXPORTAR,
    PERMISSIONS.VENTAS_IMPRIMIR
  ]),
  caja: uniquePermissions([
    PERMISSIONS.VENTAS_CREAR,
    PERMISSIONS.VENTAS_CARRITO_EDITAR,
    PERMISSIONS.VENTAS_DESCUENTO_APLICAR,
    PERMISSIONS.VENTAS_METODO_PAGO_SELECCIONAR
  ]),
  pedidos: uniquePermissions([
    PERMISSIONS.VENTAS_VER,
    PERMISSIONS.VENTAS_DETALLE_VER
  ])
});

const MODULE_ROUTE_PERMISSIONS = Object.freeze({
  dashboard: uniquePermissions([PERMISSIONS.DASHBOARD_VER]),
  personas: uniquePermissions(Object.values(PERSONAS_TAB_PERMISSIONS_MAP).flat()),
  sucursales: uniquePermissions([
    PERMISSIONS.SUCURSALES_VER,
    PERMISSIONS.SUCURSALES_CREAR,
    PERMISSIONS.SUCURSALES_EDITAR,
    PERMISSIONS.SUCURSALES_ELIMINAR,
    PERMISSIONS.SUCURSALES_ESTADO_CAMBIAR
  ]),
  inventario: uniquePermissions([
    PERMISSIONS.INVENTARIO_VER,
    ...Object.values(INVENTARIO_TAB_PERMISSIONS_MAP).flat()
  ]),
  ventas: uniquePermissions([
    PERMISSIONS.VENTAS_VER,
    ...Object.values(VENTAS_TAB_PERMISSIONS_MAP).flat()
  ]),
  cocina: uniquePermissions([
    PERMISSIONS.COCINA_VER,
    PERMISSIONS.COCINA_ACTUALIZAR_TABLERO,
    PERMISSIONS.COCINA_BUSCAR,
    PERMISSIONS.COCINA_DETALLE_VER,
    PERMISSIONS.COCINA_FILTRAR_SUCURSAL,
    PERMISSIONS.COCINA_PEDIDO_INICIAR,
    PERMISSIONS.COCINA_PEDIDO_MARCAR_LISTO,
    PERMISSIONS.COCINA_PEDIDO_ENTREGAR
  ]),
  menu: uniquePermissions([
    PERMISSIONS.MENU_VER,
    PERMISSIONS.MENU_PEDIDO_AGREGAR_ITEM,
    PERMISSIONS.MENU_PRODUCTO_DETALLE_VER,
    PERMISSIONS.MENU_PEDIDO_EDITAR_CANTIDAD,
    PERMISSIONS.MENU_PEDIDO_ELIMINAR_ITEM,
    PERMISSIONS.MENU_PEDIDO_CONFIRMAR
  ]),
  seguridad: uniquePermissions([
    PERMISSIONS.SEGURIDAD_VER,
    ...Object.values(SEGURIDAD_TAB_PERMISSIONS_MAP).flat()
  ]),
  parametros: uniquePermissions([
    PERMISSIONS.PARAMETROS_VER,
    PERMISSIONS.PARAMETROS_CATALOGOS_VER,
    PERMISSIONS.PARAMETROS_CATALOGOS_CREAR,
    PERMISSIONS.PARAMETROS_CATALOGOS_EDITAR,
    PERMISSIONS.PARAMETROS_CATALOGOS_ELIMINAR,
    PERMISSIONS.PARAMETROS_CATALOGOS_RECARGAR,
    PERMISSIONS.PARAMETROS_TIPO_DEPARTAMENTO_VER,
    PERMISSIONS.PARAMETROS_CATEGORIAS_PRODUCTOS_VER,
    PERMISSIONS.PARAMETROS_UNIDADES_MEDIDA_VER,
    PERMISSIONS.PARAMETROS_TIPO_CLIENTE_VER,
    PERMISSIONS.PARAMETROS_TIPO_NOTIFICACION_VER,
    PERMISSIONS.PARAMETROS_ESTADOS_PEDIDO_VER,
    PERMISSIONS.PARAMETROS_DISPOSITIVOS_BIOMETRICOS_VER,
    PERMISSIONS.PARAMETROS_TIPO_HORA_EXTRA_VER,
    PERMISSIONS.PARAMETROS_FACTOR_HORAS_EXTRA_VER,
    PERMISSIONS.PARAMETROS_TIPO_NOMINA_VER,
    PERMISSIONS.PARAMETROS_TIPO_NATURALEZA_VER,
    PERMISSIONS.PARAMETROS_CONCEPTO_NOMINA_VER,
    PERMISSIONS.PARAMETROS_ESTADO_PLANILLA_VER
  ]),
  configuracion: uniquePermissions([PERMISSIONS.CONFIGURACION_VER]),
  perfil: uniquePermissions([
    PERMISSIONS.PERFIL_VER,
    PERMISSIONS.PERFIL_EDITAR,
    PERMISSIONS.PERFIL_PASSWORD_CAMBIAR
  ])
});

export const ROUTE_PERMISSIONS = Object.freeze(MODULE_ROUTE_PERMISSIONS);

export const NAV_ITEM_PERMISSIONS = Object.freeze({
  '/dashboard': MODULE_ROUTE_PERMISSIONS.dashboard,
  '/dashboard/personas': MODULE_ROUTE_PERMISSIONS.personas,
  '/dashboard/sucursales': MODULE_ROUTE_PERMISSIONS.sucursales,
  '/dashboard/inventario': MODULE_ROUTE_PERMISSIONS.inventario,
  '/dashboard/ventas': MODULE_ROUTE_PERMISSIONS.ventas,
  '/dashboard/cocina': MODULE_ROUTE_PERMISSIONS.cocina,
  '/dashboard/menu': MODULE_ROUTE_PERMISSIONS.menu,
  '/dashboard/seguridad': MODULE_ROUTE_PERMISSIONS.seguridad,
  '/dashboard/parametros': MODULE_ROUTE_PERMISSIONS.parametros,
  '/dashboard/configuracion': MODULE_ROUTE_PERMISSIONS.configuracion,
  '/dashboard/perfil': MODULE_ROUTE_PERMISSIONS.perfil
});

export const INVENTARIO_TAB_PERMISSIONS = Object.freeze(INVENTARIO_TAB_PERMISSIONS_MAP);
export const PERSONAS_TAB_PERMISSIONS = Object.freeze(PERSONAS_TAB_PERMISSIONS_MAP);
export const SEGURIDAD_TAB_PERMISSIONS = Object.freeze(SEGURIDAD_TAB_PERMISSIONS_MAP);
export const VENTAS_TAB_PERMISSIONS = Object.freeze(VENTAS_TAB_PERMISSIONS_MAP);

export const MODULE_NAV_ITEMS = Object.freeze([
  { key: 'dashboard', name: 'Dashboard', path: '/dashboard', icon: 'bi-grid-1x2' },
  { key: 'sucursales', name: 'Sucursales', path: '/dashboard/sucursales', icon: 'bi-shop' },
  { key: 'personas', name: 'Personas/Empresas', path: '/dashboard/personas', icon: 'bi-people' },
  { key: 'inventario', name: 'Inventario', path: '/dashboard/inventario', icon: 'bi-box-seam' },
  { key: 'ventas', name: 'Ventas', path: '/dashboard/ventas', icon: 'bi-cart3' },
  { key: 'cocina', name: 'Cocina', path: '/dashboard/cocina', icon: 'bi-display' },
  { key: 'menu', name: 'Menu', path: '/dashboard/menu', icon: 'bi-journal-text' },
  { key: 'seguridad', name: 'Seguridad', path: '/dashboard/seguridad', icon: 'bi-shield-lock' },
  { key: 'parametros', name: 'Parametros', path: '/dashboard/parametros', icon: 'bi-sliders' },
  { key: 'configuracion', name: 'Configuracion', path: '/dashboard/configuracion', icon: 'bi-gear' }
]);

export const MODULE_PRIMARY_PERMISSION = Object.freeze({
  dashboard: PERMISSIONS.DASHBOARD_VER,
  personas: PERMISSIONS.PERSONAS_VER,
  sucursales: PERMISSIONS.SUCURSALES_VER,
  inventario: PERMISSIONS.INVENTARIO_VER,
  ventas: PERMISSIONS.VENTAS_VER,
  cocina: PERMISSIONS.COCINA_VER,
  menu: PERMISSIONS.MENU_VER,
  seguridad: PERMISSIONS.SEGURIDAD_VER,
  parametros: PERMISSIONS.PARAMETROS_VER,
  configuracion: PERMISSIONS.CONFIGURACION_VER,
  perfil: PERMISSIONS.PERFIL_VER
});

export const MODULE_TAB_CONFIG = Object.freeze({
  inventario: [
    { key: 'categorias', label: 'Categorias', icon: 'bi bi-tag', required: INVENTARIO_TAB_PERMISSIONS_MAP.categorias },
    { key: 'insumos', label: 'Insumos', icon: 'bi bi-box-seam', required: INVENTARIO_TAB_PERMISSIONS_MAP.insumos },
    { key: 'productos', label: 'Productos', icon: 'bi bi-basket', required: INVENTARIO_TAB_PERMISSIONS_MAP.productos },
    { key: 'almacenes', label: 'Almacenes', icon: 'bi bi-building', required: INVENTARIO_TAB_PERMISSIONS_MAP.almacenes },
    { key: 'alertas', label: 'Alertas', icon: 'bi bi-exclamation-triangle', required: INVENTARIO_TAB_PERMISSIONS_MAP.alertas }
  ],
  personas: [
    { key: 'personas', label: 'Personas', icon: 'bi bi-person', required: PERSONAS_TAB_PERMISSIONS_MAP.personas },
    { key: 'empresas', label: 'Empresas', icon: 'bi bi-building', required: PERSONAS_TAB_PERMISSIONS_MAP.empresas },
    { key: 'clientes', label: 'Clientes', icon: 'bi bi-people', required: PERSONAS_TAB_PERMISSIONS_MAP.clientes },
    { key: 'empleados', label: 'Empleados', icon: 'bi bi-briefcase', required: PERSONAS_TAB_PERMISSIONS_MAP.empleados },
    { key: 'usuarios', label: 'Usuarios', icon: 'bi bi-person-gear', required: PERSONAS_TAB_PERMISSIONS_MAP.usuarios },
    { key: 'roles', label: 'Roles y permisos', icon: 'bi bi-person-lock', required: PERSONAS_TAB_PERMISSIONS_MAP.roles }
  ],
  seguridad: [
    { key: 'sesiones', label: 'Sesiones activas', icon: 'bi bi-laptop', required: SEGURIDAD_TAB_PERMISSIONS_MAP.sesiones },
    { key: 'usuarios', label: 'Usuarios', icon: 'bi bi-people', required: SEGURIDAD_TAB_PERMISSIONS_MAP.usuarios },
    { key: 'password', label: 'Politicas de contrasena', icon: 'bi bi-key', required: SEGURIDAD_TAB_PERMISSIONS_MAP.password },
    { key: 'logins', label: 'Logs de login', icon: 'bi bi-journal-text', required: SEGURIDAD_TAB_PERMISSIONS_MAP.logins }
  ],
  ventas: [
    { key: 'ventas', label: 'Ventas', icon: 'bi bi-receipt-cutoff', required: VENTAS_TAB_PERMISSIONS_MAP.ventas },
    { key: 'caja', label: 'Caja', icon: 'bi bi-cart3', required: VENTAS_TAB_PERMISSIONS_MAP.caja },
    { key: 'pedidos', label: 'Pedidos', icon: 'bi bi-journal-richtext', required: VENTAS_TAB_PERMISSIONS_MAP.pedidos }
  ]
});

export const isTabAllowed = (permissionSet, tabKey, map, options = {}) => {
  const required = map?.[tabKey] || [];
  return hasAnyPermission(permissionSet, required, options);
};

export const resolveFirstAllowedTab = (tabKeys, permissionSet, map, fallbackKey, options = {}) => {
  const keys = Array.isArray(tabKeys) ? tabKeys : [];
  const firstAllowed = keys.find((key) => isTabAllowed(permissionSet, key, map, options));
  return firstAllowed || fallbackKey || keys[0] || null;
};

export const getModulePermissions = (moduleKey) => MODULE_ROUTE_PERMISSIONS[moduleKey] || [];

export const canAccessModule = (permissionSet, moduleKey, options = {}) =>
  hasAnyPermission(permissionSet, getModulePermissions(moduleKey), options);

export const getVisibleModuleItems = (permissionSet, options = {}) =>
  MODULE_NAV_ITEMS.filter((item) => canAccessModule(permissionSet, item.key, options));

export const getAllowedTabs = (moduleKey, permissionSet, options = {}) =>
  (MODULE_TAB_CONFIG[moduleKey] || []).filter((tab) =>
    hasAnyPermission(permissionSet, tab.required || [], options)
  );

export const getFirstAccessibleDashboardPath = (permissionSet, options = {}) => {
  const nextModule = MODULE_NAV_ITEMS.find(
    (item) => item.key !== 'dashboard' && canAccessModule(permissionSet, item.key, options)
  );

  if (nextModule) return nextModule.path;

  if (canAccessModule(permissionSet, 'perfil', options)) {
    return '/dashboard/perfil';
  }

  return null;
};
