import { PLANILLAS_NAV_TAB_KEYS, PLANILLAS_NAV_TABS } from '../modules/planillas/navigation';

const uniquePermissions = (values) => {
  const seen = new Set();
  const result = [];

  (Array.isArray(values) ? values : []).forEach((value) => {
    const normalized = String(value ?? '').trim().toUpperCase();
    if (!normalized || seen.has(normalized)) return;
    seen.add(normalized);
    result.push(normalized);
  });

  return result;
};

const PERMISSION_VALUES = Object.freeze({
  DASHBOARD_VER: 'DASHBOARD_VER',
  PERFIL_VER: 'PERFIL_VER',
  PERFIL_EDITAR: 'PERFIL_EDITAR',
  PERFIL_PASSWORD_CAMBIAR: 'PERFIL_PASSWORD_CAMBIAR',

  PERSONAS_MODULO_VER: 'PERSONAS_MODULO_VER',
  PERSONAS_LISTADO_VER: 'PERSONAS_LISTADO_VER',
  PERSONAS_DETALLE_VER: 'PERSONAS_DETALLE_VER',
  PERSONAS_VER: 'PERSONAS_VER',
  PERSONAS_CREAR: 'PERSONAS_CREAR',
  PERSONAS_CREAR_DESDE_CLIENTES: 'PERSONAS_CREAR_DESDE_CLIENTES',
  PERSONAS_EDITAR: 'PERSONAS_EDITAR',
  PERSONAS_ELIMINAR: 'PERSONAS_ELIMINAR',
  PERSONAS_BUSCAR: 'PERSONAS_BUSCAR',
  PERSONAS_USAR_FILTROS: 'PERSONAS_USAR_FILTROS',
  PERSONAS_ESTADO_CAMBIAR: 'PERSONAS_ESTADO_CAMBIAR',
  PERSONAS_VER_SOLO_RELACIONADOS: 'PERSONAS_VER_SOLO_RELACIONADOS',
  EMPRESAS_MODULO_VER: 'EMPRESAS_MODULO_VER',
  EMPRESAS_LISTADO_VER: 'EMPRESAS_LISTADO_VER',
  EMPRESAS_DETALLE_VER: 'EMPRESAS_DETALLE_VER',
  EMPRESAS_VER: 'EMPRESAS_VER',
  EMPRESAS_CREAR: 'EMPRESAS_CREAR',
  EMPRESAS_CREAR_DESDE_CLIENTES: 'EMPRESAS_CREAR_DESDE_CLIENTES',
  EMPRESAS_EDITAR: 'EMPRESAS_EDITAR',
  EMPRESAS_ELIMINAR: 'EMPRESAS_ELIMINAR',
  EMPRESAS_BUSCAR: 'EMPRESAS_BUSCAR',
  EMPRESAS_USAR_FILTROS: 'EMPRESAS_USAR_FILTROS',
  EMPRESAS_ESTADO_CAMBIAR: 'EMPRESAS_ESTADO_CAMBIAR',
  EMPRESAS_IMAGEN_SUBIR: 'EMPRESAS_IMAGEN_SUBIR',
  EMPRESAS_VER_SOLO_RELACIONADOS: 'EMPRESAS_VER_SOLO_RELACIONADOS',
  CLIENTES_MODULO_VER: 'CLIENTES_MODULO_VER',
  CLIENTES_LISTADO_VER: 'CLIENTES_LISTADO_VER',
  CLIENTES_DETALLE_VER: 'CLIENTES_DETALLE_VER',
  CLIENTES_VER: 'CLIENTES_VER',
  CLIENTES_CREAR: 'CLIENTES_CREAR',
  CLIENTES_EDITAR: 'CLIENTES_EDITAR',
  CLIENTES_ELIMINAR: 'CLIENTES_ELIMINAR',
  CLIENTES_BUSCAR: 'CLIENTES_BUSCAR',
  CLIENTES_USAR_FILTROS: 'CLIENTES_USAR_FILTROS',
  CLIENTES_ESTADO_CAMBIAR: 'CLIENTES_ESTADO_CAMBIAR',
  CLIENTES_PUNTOS_AJUSTAR: 'CLIENTES_PUNTOS_AJUSTAR',
  CLIENTES_VER_SOLO_RELACIONADOS: 'CLIENTES_VER_SOLO_RELACIONADOS',
  EMPLEADOS_MODULO_VER: 'EMPLEADOS_MODULO_VER',
  EMPLEADOS_LISTADO_VER: 'EMPLEADOS_LISTADO_VER',
  EMPLEADOS_DETALLE_VER: 'EMPLEADOS_DETALLE_VER',
  EMPLEADOS_VER: 'EMPLEADOS_VER',
  EMPLEADOS_CREAR: 'EMPLEADOS_CREAR',
  EMPLEADOS_EDITAR: 'EMPLEADOS_EDITAR',
  EMPLEADOS_ELIMINAR: 'EMPLEADOS_ELIMINAR',
  EMPLEADOS_BUSCAR: 'EMPLEADOS_BUSCAR',
  EMPLEADOS_USAR_FILTROS: 'EMPLEADOS_USAR_FILTROS',
  EMPLEADOS_ESTADO_CAMBIAR: 'EMPLEADOS_ESTADO_CAMBIAR',
  EMPLEADOS_IMAGEN_SUBIR: 'EMPLEADOS_IMAGEN_SUBIR',
  EMPLEADOS_FICHA_IMPRIMIR: 'EMPLEADOS_FICHA_IMPRIMIR',
  EMPLEADOS_VER_SOLO_RELACIONADOS: 'EMPLEADOS_VER_SOLO_RELACIONADOS',
  EMPLEADOS_VER_SOLO_PROPIOS: 'EMPLEADOS_VER_SOLO_PROPIOS',
  PLANILLAS_MODULO_VER: 'PLANILLAS_MODULO_VER',
  PLANILLAS_LISTADO_VER: 'PLANILLAS_LISTADO_VER',
  PLANILLAS_DETALLE_VER: 'PLANILLAS_DETALLE_VER',
  PLANILLAS_GENERAR: 'PLANILLAS_GENERAR',
  PLANILLAS_RECALCULAR: 'PLANILLAS_RECALCULAR',
  PLANILLAS_ADELANTOS_APLICAR: 'PLANILLAS_ADELANTOS_APLICAR',
  PLANILLAS_MOVIMIENTO_REGISTRAR: 'PLANILLAS_MOVIMIENTO_REGISTRAR',
  PLANILLAS_MOVIMIENTO_ANULAR: 'PLANILLAS_MOVIMIENTO_ANULAR',
  PLANILLAS_CERRAR: 'PLANILLAS_CERRAR',
  PLANILLAS_PAGAR: 'PLANILLAS_PAGAR',
  PLANILLAS_ANULAR: 'PLANILLAS_ANULAR',
  PLANILLAS_AUDITORIA_VER: 'PLANILLAS_AUDITORIA_VER',
  USUARIOS_MODULO_VER: 'USUARIOS_MODULO_VER',
  USUARIOS_LISTADO_VER: 'USUARIOS_LISTADO_VER',
  USUARIOS_DETALLE_VER: 'USUARIOS_DETALLE_VER',
  USUARIOS_VER: 'USUARIOS_VER',
  USUARIOS_CREAR: 'USUARIOS_CREAR',
  USUARIOS_EDITAR: 'USUARIOS_EDITAR',
  USUARIOS_ELIMINAR: 'USUARIOS_ELIMINAR',
  USUARIOS_BUSCAR: 'USUARIOS_BUSCAR',
  USUARIOS_USAR_FILTROS: 'USUARIOS_USAR_FILTROS',
  USUARIOS_ESTADO_CAMBIAR: 'USUARIOS_ESTADO_CAMBIAR',
  USUARIOS_ROL_ASIGNAR: 'USUARIOS_ROL_ASIGNAR',
  USUARIOS_PASSWORD_RESETEAR: 'USUARIOS_PASSWORD_RESETEAR',
  USUARIOS_PASSWORD_CAMBIAR_PROPIO: 'USUARIOS_PASSWORD_CAMBIAR_PROPIO',
  USUARIOS_IMAGEN_SUBIR: 'USUARIOS_IMAGEN_SUBIR',
  USUARIOS_IMAGEN_ELIMINAR: 'USUARIOS_IMAGEN_ELIMINAR',
  USUARIOS_VER_SOLO_PROPIOS: 'USUARIOS_VER_SOLO_PROPIOS',
  USUARIOS_VER_SOLO_RELACIONADOS: 'USUARIOS_VER_SOLO_RELACIONADOS',
  ROLES_PERMISOS_MODULO_VER: 'ROLES_PERMISOS_MODULO_VER',
  ROLES_PERMISOS_ROLES_LISTADO_VER: 'ROLES_PERMISOS_ROLES_LISTADO_VER',
  ROLES_PERMISOS_ROLES_DETALLE_VER: 'ROLES_PERMISOS_ROLES_DETALLE_VER',
  ROLES_PERMISOS_ROLES_CREAR: 'ROLES_PERMISOS_ROLES_CREAR',
  ROLES_PERMISOS_ROLES_EDITAR: 'ROLES_PERMISOS_ROLES_EDITAR',
  ROLES_PERMISOS_ROLES_ELIMINAR: 'ROLES_PERMISOS_ROLES_ELIMINAR',
  ROLES_PERMISOS_ROLES_BUSCAR: 'ROLES_PERMISOS_ROLES_BUSCAR',
  ROLES_PERMISOS_PERMISOS_LISTADO_VER: 'ROLES_PERMISOS_PERMISOS_LISTADO_VER',
  ROLES_PERMISOS_PERMISOS_BUSCAR: 'ROLES_PERMISOS_PERMISOS_BUSCAR',
  ROLES_PERMISOS_PERMISOS_TOGGLE: 'ROLES_PERMISOS_PERMISOS_TOGGLE',
  ROLES_PERMISOS_PERMISOS_SELECCIONAR_TODOS: 'ROLES_PERMISOS_PERMISOS_SELECCIONAR_TODOS',
  ROLES_PERMISOS_PERMISOS_QUITAR_TODOS: 'ROLES_PERMISOS_PERMISOS_QUITAR_TODOS',
  ROLES_PERMISOS_PERMISOS_GUARDAR: 'ROLES_PERMISOS_PERMISOS_GUARDAR',
  ROLES_PERMISOS_AUDITORIA_VER: 'ROLES_PERMISOS_AUDITORIA_VER',
  ROLES_PERMISOS_VER: 'ROLES_PERMISOS_VER',
  ROLES_PERMISOS_DETALLE_VER: 'ROLES_PERMISOS_DETALLE_VER',
  ROLES_PERMISOS_EDITAR: 'ROLES_PERMISOS_EDITAR',

  SUCURSALES_VER: 'SUCURSALES_VER',
  SUCURSALES_CREAR: 'SUCURSALES_CREAR',
  SUCURSALES_EDITAR: 'SUCURSALES_EDITAR',
  SUCURSALES_ELIMINAR: 'SUCURSALES_ELIMINAR',
  SUCURSALES_ESTADO_CAMBIAR: 'SUCURSALES_ESTADO_CAMBIAR',

  INVENTARIO_VER: 'INVENTARIO_VER',
  INVENTARIO_CATEGORIAS_VER: 'INVENTARIO_CATEGORIAS_VER',
  INVENTARIO_CATEGORIAS_CREAR: 'INVENTARIO_CATEGORIAS_CREAR',
  INVENTARIO_CATEGORIAS_EDITAR: 'INVENTARIO_CATEGORIAS_EDITAR',
  INVENTARIO_CATEGORIAS_ELIMINAR: 'INVENTARIO_CATEGORIAS_ELIMINAR',
  INVENTARIO_CATEGORIAS_ESTADO_CAMBIAR: 'INVENTARIO_CATEGORIAS_ESTADO_CAMBIAR',
  INVENTARIO_CATEGORIAS_INSUMOS_VER: 'INVENTARIO_CATEGORIAS_INSUMOS_VER',
  INVENTARIO_CATEGORIAS_INSUMOS_CREAR: 'INVENTARIO_CATEGORIAS_INSUMOS_CREAR',
  INVENTARIO_CATEGORIAS_INSUMOS_EDITAR: 'INVENTARIO_CATEGORIAS_INSUMOS_EDITAR',
  INVENTARIO_CATEGORIAS_INSUMOS_ELIMINAR: 'INVENTARIO_CATEGORIAS_INSUMOS_ELIMINAR',
  INVENTARIO_CATEGORIAS_INSUMOS_ESTADO_CAMBIAR: 'INVENTARIO_CATEGORIAS_INSUMOS_ESTADO_CAMBIAR',
  INVENTARIO_INSUMOS_VER: 'INVENTARIO_INSUMOS_VER',
  INVENTARIO_INSUMOS_DETALLE_VER: 'INVENTARIO_INSUMOS_DETALLE_VER',
  INVENTARIO_INSUMOS_CREAR: 'INVENTARIO_INSUMOS_CREAR',
  INVENTARIO_INSUMOS_EDITAR: 'INVENTARIO_INSUMOS_EDITAR',
  INVENTARIO_INSUMOS_ELIMINAR: 'INVENTARIO_INSUMOS_ELIMINAR',
  INVENTARIO_INSUMOS_ESTADO_CAMBIAR: 'INVENTARIO_INSUMOS_ESTADO_CAMBIAR',
  INVENTARIO_PRODUCTOS_VER: 'INVENTARIO_PRODUCTOS_VER',
  INVENTARIO_PRODUCTOS_CREAR: 'INVENTARIO_PRODUCTOS_CREAR',
  INVENTARIO_PRODUCTOS_EDITAR: 'INVENTARIO_PRODUCTOS_EDITAR',
  INVENTARIO_PRODUCTOS_ELIMINAR: 'INVENTARIO_PRODUCTOS_ELIMINAR',
  INVENTARIO_PRODUCTOS_DETALLE_VER: 'INVENTARIO_PRODUCTOS_DETALLE_VER',
  INVENTARIO_PRODUCTOS_ESTADO_CAMBIAR: 'INVENTARIO_PRODUCTOS_ESTADO_CAMBIAR',
  INVENTARIO_PRODUCTOS_IMAGEN_SUBIR: 'INVENTARIO_PRODUCTOS_IMAGEN_SUBIR',
  INVENTARIO_PRODUCTOS_IMAGEN_ELIMINAR: 'INVENTARIO_PRODUCTOS_IMAGEN_ELIMINAR',
  INVENTARIO_ALMACENES_VER: 'INVENTARIO_ALMACENES_VER',
  INVENTARIO_ALMACENES_DETALLE_VER: 'INVENTARIO_ALMACENES_DETALLE_VER',
  INVENTARIO_ALMACENES_CREAR: 'INVENTARIO_ALMACENES_CREAR',
  INVENTARIO_ALMACENES_EDITAR: 'INVENTARIO_ALMACENES_EDITAR',
  INVENTARIO_ALMACENES_ELIMINAR: 'INVENTARIO_ALMACENES_ELIMINAR',
  INVENTARIO_ALMACENES_ESTADO_CAMBIAR: 'INVENTARIO_ALMACENES_ESTADO_CAMBIAR',
  INVENTARIO_PROVEEDORES_VER: 'INVENTARIO_PROVEEDORES_VER',
  INVENTARIO_PROVEEDORES_DETALLE_VER: 'INVENTARIO_PROVEEDORES_DETALLE_VER',
  INVENTARIO_PROVEEDORES_CREAR: 'INVENTARIO_PROVEEDORES_CREAR',
  INVENTARIO_PROVEEDORES_EDITAR: 'INVENTARIO_PROVEEDORES_EDITAR',
  INVENTARIO_PROVEEDORES_ELIMINAR: 'INVENTARIO_PROVEEDORES_ELIMINAR',
  INVENTARIO_PROVEEDORES_ESTADO_CAMBIAR: 'INVENTARIO_PROVEEDORES_ESTADO_CAMBIAR',
  INVENTARIO_ARCHIVOS_VER: 'INVENTARIO_ARCHIVOS_VER',
  INVENTARIO_ARCHIVOS_SUBIR: 'INVENTARIO_ARCHIVOS_SUBIR',
  INVENTARIO_ARCHIVOS_ELIMINAR: 'INVENTARIO_ARCHIVOS_ELIMINAR',
  INVENTARIO_MOVIMIENTOS_VER: 'INVENTARIO_MOVIMIENTOS_VER',
  INVENTARIO_MOVIMIENTOS_CREAR: 'INVENTARIO_MOVIMIENTOS_CREAR',
  INVENTARIO_MOVIMIENTOS_EDITAR: 'INVENTARIO_MOVIMIENTOS_EDITAR',
  INVENTARIO_MOVIMIENTOS_ELIMINAR: 'INVENTARIO_MOVIMIENTOS_ELIMINAR',
  INVENTARIO_ALERTAS_VER: 'INVENTARIO_ALERTAS_VER',
  INVENTARIO_ALERTAS_ACTUALIZAR: 'INVENTARIO_ALERTAS_ACTUALIZAR',
  INVENTARIO_ALERTAS_STOCK_MINIMO_EDITAR: 'INVENTARIO_ALERTAS_STOCK_MINIMO_EDITAR',
  // AM: permisos del submodulo de ordenes de compra.
  INVENTARIO_ORDENES_COMPRA_VER: 'INVENTARIO_ORDENES_COMPRA_VER',
  INVENTARIO_ORDENES_COMPRA_CREAR: 'INVENTARIO_ORDENES_COMPRA_CREAR',
  INVENTARIO_ORDENES_COMPRA_VER_TODAS: 'INVENTARIO_ORDENES_COMPRA_VER_TODAS',
  INVENTARIO_ORDENES_COMPRA_GESTIONAR: 'INVENTARIO_ORDENES_COMPRA_GESTIONAR',
  INVENTARIO_ORDENES_COMPRA_CONVERTIR: 'INVENTARIO_ORDENES_COMPRA_CONVERTIR',
  INVENTARIO_ORDENES_COMPRA_ABASTECER: 'INVENTARIO_ORDENES_COMPRA_ABASTECER',
  INVENTARIO_ORDENES_COMPRA_RECEPCIONAR: 'INVENTARIO_ORDENES_COMPRA_RECEPCIONAR',
  INVENTARIO_OC_VER_FLUJO: 'INVENTARIO_OC_VER_FLUJO',
  INVENTARIO_OC_VER_DETALLE: 'INVENTARIO_OC_VER_DETALLE',
  INVENTARIO_OC_CREAR_SOLICITUD: 'INVENTARIO_OC_CREAR_SOLICITUD',
  INVENTARIO_OC_EDITAR_SOLICITUD: 'INVENTARIO_OC_EDITAR_SOLICITUD',
  INVENTARIO_OC_APROBAR: 'INVENTARIO_OC_APROBAR',
  INVENTARIO_OC_RECHAZAR: 'INVENTARIO_OC_RECHAZAR',
  INVENTARIO_OC_CANCELAR: 'INVENTARIO_OC_CANCELAR',
  INVENTARIO_OC_RECEPCIONAR: 'INVENTARIO_OC_RECEPCIONAR',
  INVENTARIO_OC_CONVERTIR_CONTINUAR: 'INVENTARIO_OC_CONVERTIR_CONTINUAR',
  INVENTARIO_OC_ABASTECER: 'INVENTARIO_OC_ABASTECER',
  INVENTARIO_OC_SUBIR_FACTURA: 'INVENTARIO_OC_SUBIR_FACTURA',
  INVENTARIO_OC_SUBIR_DEPOSITO: 'INVENTARIO_OC_SUBIR_DEPOSITO',
  INVENTARIO_OC_VER_EVIDENCIAS: 'INVENTARIO_OC_VER_EVIDENCIAS',
  INVENTARIO_OC_VER_HISTORIAL: 'INVENTARIO_OC_VER_HISTORIAL',
  INVENTARIO_OC_CAMBIAR_ESTADO: 'INVENTARIO_OC_CAMBIAR_ESTADO',
  INVENTARIO_OC_REVISAR_SOLICITUD_ITEM: 'INVENTARIO_OC_REVISAR_SOLICITUD_ITEM',
  INVENTARIO_OC_ATENDER_SOLICITUD_ITEM: 'INVENTARIO_OC_ATENDER_SOLICITUD_ITEM',
  // AM: permisos del submodulo Inventario > Mobiliario.
  INVENTARIO_MOBILIARIO_VER: 'INVENTARIO_MOBILIARIO_VER',
  INVENTARIO_MOBILIARIO_DETALLE_VER: 'INVENTARIO_MOBILIARIO_DETALLE_VER',
  INVENTARIO_MOBILIARIO_CREAR: 'INVENTARIO_MOBILIARIO_CREAR',
  INVENTARIO_MOBILIARIO_EDITAR: 'INVENTARIO_MOBILIARIO_EDITAR',
  INVENTARIO_MOBILIARIO_ESTADO_CAMBIAR: 'INVENTARIO_MOBILIARIO_ESTADO_CAMBIAR',

  VENTAS_VER: 'VENTAS_VER',
  VENTAS_CIERRES_VER: 'VENTAS_CIERRES_VER',
  VENTAS_CIERRES_GESTIONAR: 'VENTAS_CIERRES_GESTIONAR',
  VENTAS_CAJAS_MODULO_VER: 'VENTAS_CAJAS_MODULO_VER',
  VENTAS_CAJAS_LISTADO_VER: 'VENTAS_CAJAS_LISTADO_VER',
  VENTAS_CAJAS_DETALLE_VER: 'VENTAS_CAJAS_DETALLE_VER',
  VENTAS_CAJAS_SESION_ABRIR: 'VENTAS_CAJAS_SESION_ABRIR',
  VENTAS_CAJAS_SESION_CERRAR: 'VENTAS_CAJAS_SESION_CERRAR',
  VENTAS_CAJAS_PARTICIPANTES_GESTIONAR: 'VENTAS_CAJAS_PARTICIPANTES_GESTIONAR',
  VENTAS_CAJAS_ARQUEO_REGISTRAR: 'VENTAS_CAJAS_ARQUEO_REGISTRAR',
  VENTAS_CAJAS_MOVIMIENTO_MANUAL_REGISTRAR: 'VENTAS_CAJAS_MOVIMIENTO_MANUAL_REGISTRAR',
  VENTAS_CAJAS_INCIDENCIA_GESTIONAR: 'VENTAS_CAJAS_INCIDENCIA_GESTIONAR',
  VENTAS_CAJAS_REPORTE_VER: 'VENTAS_CAJAS_REPORTE_VER',
  VENTAS_CAJAS_MULTISUCURSAL_VER: 'VENTAS_CAJAS_MULTISUCURSAL_VER',
  VENTAS_CAJAS_DIFERENCIA_RESOLVER: 'VENTAS_CAJAS_DIFERENCIA_RESOLVER',
  VENTAS_CREAR: 'VENTAS_CREAR',
  VENTAS_EXPORTAR: 'VENTAS_EXPORTAR',
  VENTAS_IMPRIMIR: 'VENTAS_IMPRIMIR',
  VENTAS_DETALLE_VER: 'VENTAS_DETALLE_VER',
  VENTAS_CARRITO_EDITAR: 'VENTAS_CARRITO_EDITAR',
  VENTAS_DESCUENTO_APLICAR: 'VENTAS_DESCUENTO_APLICAR',
  VENTAS_DESCUENTOS_CATALOGO_VER: 'VENTAS_DESCUENTOS_CATALOGO_VER',
  VENTAS_DESCUENTOS_CATALOGO_CREAR: 'VENTAS_DESCUENTOS_CATALOGO_CREAR',
  VENTAS_DESCUENTOS_CATALOGO_EDITAR: 'VENTAS_DESCUENTOS_CATALOGO_EDITAR',
  VENTAS_DESCUENTOS_CATALOGO_ESTADO_CAMBIAR: 'VENTAS_DESCUENTOS_CATALOGO_ESTADO_CAMBIAR',
  VENTAS_METODO_PAGO_SELECCIONAR: 'VENTAS_METODO_PAGO_SELECCIONAR',

  COCINA_VER: 'COCINA_VER',
  COCINA_ACTUALIZAR_TABLERO: 'COCINA_ACTUALIZAR_TABLERO',
  COCINA_BUSCAR: 'COCINA_BUSCAR',
  COCINA_DETALLE_VER: 'COCINA_DETALLE_VER',
  COCINA_FILTRAR_SUCURSAL: 'COCINA_FILTRAR_SUCURSAL',
  COCINA_PEDIDO_INICIAR: 'COCINA_PEDIDO_INICIAR',
  COCINA_PEDIDO_MARCAR_LISTO: 'COCINA_PEDIDO_MARCAR_LISTO',
  COCINA_PEDIDO_ENTREGAR: 'COCINA_PEDIDO_ENTREGAR',

  MENU_VER: 'MENU_VER',
  MENU_PEDIDO_AGREGAR_ITEM: 'MENU_PEDIDO_AGREGAR_ITEM',
  MENU_PRODUCTO_DETALLE_VER: 'MENU_PRODUCTO_DETALLE_VER',
  MENU_PEDIDO_EDITAR_CANTIDAD: 'MENU_PEDIDO_EDITAR_CANTIDAD',
  MENU_PEDIDO_ELIMINAR_ITEM: 'MENU_PEDIDO_ELIMINAR_ITEM',
  MENU_PEDIDO_CONFIRMAR: 'MENU_PEDIDO_CONFIRMAR',

  SEGURIDAD_VER: 'SEGURIDAD_VER',
  SEGURIDAD_CONFIG_VER: 'SEGURIDAD_CONFIG_VER',
  SEGURIDAD_CONFIG_EDITAR: 'SEGURIDAD_CONFIG_EDITAR',
  SEGURIDAD_SESIONES_VER: 'SEGURIDAD_SESIONES_VER',
  SEGURIDAD_SESIONES_VER_GLOBAL: 'SEGURIDAD_SESIONES_VER_GLOBAL',
  SEGURIDAD_SESIONES_CERRAR: 'SEGURIDAD_SESIONES_CERRAR',
  SEGURIDAD_SESIONES_CERRAR_OTRAS: 'SEGURIDAD_SESIONES_CERRAR_OTRAS',
  SEGURIDAD_SESIONES_CERRAR_GLOBAL: 'SEGURIDAD_SESIONES_CERRAR_GLOBAL',
  SEGURIDAD_SESIONES_CERRAR_GLOBAL_MENOS_ACTUAL: 'SEGURIDAD_SESIONES_CERRAR_GLOBAL_MENOS_ACTUAL',
  SEGURIDAD_USUARIOS_VER: 'SEGURIDAD_USUARIOS_VER',
  SEGURIDAD_USUARIOS_AUDITORIA_VER: 'SEGURIDAD_USUARIOS_AUDITORIA_VER',
  SEGURIDAD_USUARIOS_AUDITORIA_SESIONES_VER: 'SEGURIDAD_USUARIOS_AUDITORIA_SESIONES_VER',
  SEGURIDAD_USUARIOS_AUDITORIA_LOGINS_VER: 'SEGURIDAD_USUARIOS_AUDITORIA_LOGINS_VER',
  SEGURIDAD_USUARIOS_SESIONES_CERRAR: 'SEGURIDAD_USUARIOS_SESIONES_CERRAR',
  SEGURIDAD_LOGINS_VER: 'SEGURIDAD_LOGINS_VER',

  PARAMETROS_VER: 'PARAMETROS_VER',
  PARAMETROS_CATALOGOS_VER: 'PARAMETROS_CATALOGOS_VER',
  PARAMETROS_CATALOGOS_CREAR: 'PARAMETROS_CATALOGOS_CREAR',
  PARAMETROS_CATALOGOS_EDITAR: 'PARAMETROS_CATALOGOS_EDITAR',
  PARAMETROS_CATALOGOS_ELIMINAR: 'PARAMETROS_CATALOGOS_ELIMINAR',
  PARAMETROS_CATALOGOS_RECARGAR: 'PARAMETROS_CATALOGOS_RECARGAR',
  PARAMETROS_TIPO_DEPARTAMENTO_VER: 'PARAMETROS_TIPO_DEPARTAMENTO_VER',
  PARAMETROS_CATEGORIAS_PRODUCTOS_VER: 'PARAMETROS_CATEGORIAS_PRODUCTOS_VER',
  PARAMETROS_UNIDADES_MEDIDA_VER: 'PARAMETROS_UNIDADES_MEDIDA_VER',
  PARAMETROS_TIPO_CLIENTE_VER: 'PARAMETROS_TIPO_CLIENTE_VER',
  PARAMETROS_TIPO_NOTIFICACION_VER: 'PARAMETROS_TIPO_NOTIFICACION_VER',
  PARAMETROS_ESTADOS_PEDIDO_VER: 'PARAMETROS_ESTADOS_PEDIDO_VER',
  PARAMETROS_DISPOSITIVOS_BIOMETRICOS_VER: 'PARAMETROS_DISPOSITIVOS_BIOMETRICOS_VER',
  PARAMETROS_TIPO_HORA_EXTRA_VER: 'PARAMETROS_TIPO_HORA_EXTRA_VER',
  PARAMETROS_FACTOR_HORAS_EXTRA_VER: 'PARAMETROS_FACTOR_HORAS_EXTRA_VER',
  PARAMETROS_TIPO_NOMINA_VER: 'PARAMETROS_TIPO_NOMINA_VER',
  PARAMETROS_TIPO_NATURALEZA_VER: 'PARAMETROS_TIPO_NATURALEZA_VER',
  PARAMETROS_CONCEPTO_NOMINA_VER: 'PARAMETROS_CONCEPTO_NOMINA_VER',
  PARAMETROS_ESTADO_PLANILLA_VER: 'PARAMETROS_ESTADO_PLANILLA_VER',

  CONFIGURACION_VER: 'CONFIGURACION_VER',

  FIDELIZACION_VER_PANEL: 'FIDELIZACION_VER_PANEL',
  FIDELIZACION_VER_CLIENTES: 'FIDELIZACION_VER_CLIENTES',
  FIDELIZACION_VER_MOVIMIENTOS: 'FIDELIZACION_VER_MOVIMIENTOS',
  FIDELIZACION_CONFIGURAR_REGLAS: 'FIDELIZACION_CONFIGURAR_REGLAS',
  FIDELIZACION_GESTIONAR_PRODUCTOS_CANJEABLES: 'FIDELIZACION_GESTIONAR_PRODUCTOS_CANJEABLES',
  FIDELIZACION_CANJEAR_PRESENCIAL: 'FIDELIZACION_CANJEAR_PRESENCIAL',
  FIDELIZACION_VER_CANJES: 'FIDELIZACION_VER_CANJES',
  FIDELIZACION_VER_MULTISUCURSAL: 'FIDELIZACION_VER_MULTISUCURSAL',
  CONFIGURACION_EMAIL_CAMPAIGNS_VER: 'CONFIGURACION_EMAIL_CAMPAIGNS_VER',
  CONFIGURACION_EMAIL_CAMPAIGNS_GESTIONAR: 'CONFIGURACION_EMAIL_CAMPAIGNS_GESTIONAR'
});

export const PERMISSIONS = Object.freeze({
  ...PERMISSION_VALUES,
  CATEGORIAS_VER: PERMISSION_VALUES.INVENTARIO_CATEGORIAS_VER,
  INSUMOS_VER: PERMISSION_VALUES.INVENTARIO_INSUMOS_VER,
  PRODUCTOS_VER: PERMISSION_VALUES.INVENTARIO_PRODUCTOS_VER,
  ALMACENES_VER: PERMISSION_VALUES.INVENTARIO_ALMACENES_VER,
  MOVIMIENTOS_VER: PERMISSION_VALUES.INVENTARIO_MOVIMIENTOS_VER,
  ALERTAS_VER: PERMISSION_VALUES.INVENTARIO_ALERTAS_VER,
  ALERTAS_STOCK_MINIMO_EDITAR: PERMISSION_VALUES.INVENTARIO_ALERTAS_STOCK_MINIMO_EDITAR,
  MENU_DETALLE_VER: PERMISSION_VALUES.MENU_PRODUCTO_DETALLE_VER,
  MENU_PRODUCTO_AGREGAR: PERMISSION_VALUES.MENU_PEDIDO_AGREGAR_ITEM,
  MENU_PEDIDO_EDITAR: PERMISSION_VALUES.MENU_PEDIDO_EDITAR_CANTIDAD,
  PARAMETROS_CATALOGO_VER: PERMISSION_VALUES.PARAMETROS_CATALOGOS_VER,
  PARAMETROS_CATALOGO_CREAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_CREAR,
  PARAMETROS_CATALOGO_EDITAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_EDITAR,
  PARAMETROS_CATALOGO_ELIMINAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_ELIMINAR,
  PARAMETROS_CATALOGO_RECARGAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_RECARGAR,
  SEGURIDAD_LOGS_VER: PERMISSION_VALUES.SEGURIDAD_LOGINS_VER,
  COCINA_REFRESCAR: PERMISSION_VALUES.COCINA_ACTUALIZAR_TABLERO,
  COCINA_ESTADO_CAMBIAR: PERMISSION_VALUES.COCINA_PEDIDO_MARCAR_LISTO,
  USUARIOS_FOTO_EDITAR: PERMISSION_VALUES.USUARIOS_IMAGEN_SUBIR,
  VENTAS_CIERRES_VER: PERMISSION_VALUES.VENTAS_CAJAS_MODULO_VER
});

const PERMISSION_ALIASES = Object.freeze({
  CATEGORIAS_VER: PERMISSION_VALUES.INVENTARIO_CATEGORIAS_VER,
  INSUMOS_VER: PERMISSION_VALUES.INVENTARIO_INSUMOS_VER,
  PRODUCTOS_VER: PERMISSION_VALUES.INVENTARIO_PRODUCTOS_VER,
  ALMACENES_VER: PERMISSION_VALUES.INVENTARIO_ALMACENES_VER,
  MOVIMIENTOS_VER: PERMISSION_VALUES.INVENTARIO_MOVIMIENTOS_VER,
  ALERTAS_VER: PERMISSION_VALUES.INVENTARIO_ALERTAS_VER,
  ALERTAS_STOCK_MINIMO_EDITAR: PERMISSION_VALUES.INVENTARIO_ALERTAS_STOCK_MINIMO_EDITAR,
  MENU_DETALLE_VER: PERMISSION_VALUES.MENU_PRODUCTO_DETALLE_VER,
  MENU_PRODUCTO_AGREGAR: PERMISSION_VALUES.MENU_PEDIDO_AGREGAR_ITEM,
  MENU_PEDIDO_EDITAR: PERMISSION_VALUES.MENU_PEDIDO_EDITAR_CANTIDAD,
  PARAMETROS_CATALOGO_VER: PERMISSION_VALUES.PARAMETROS_CATALOGOS_VER,
  PARAMETROS_CATALOGO_CREAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_CREAR,
  PARAMETROS_CATALOGO_EDITAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_EDITAR,
  PARAMETROS_CATALOGO_ELIMINAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_ELIMINAR,
  PARAMETROS_CATALOGO_RECARGAR: PERMISSION_VALUES.PARAMETROS_CATALOGOS_RECARGAR,
  SEGURIDAD_LOGS_VER: PERMISSION_VALUES.SEGURIDAD_LOGINS_VER,
  COCINA_REFRESCAR: PERMISSION_VALUES.COCINA_ACTUALIZAR_TABLERO,
  COCINA_ESTADO_CAMBIAR: PERMISSION_VALUES.COCINA_PEDIDO_MARCAR_LISTO,
  USUARIOS_FOTO_EDITAR: PERMISSION_VALUES.USUARIOS_IMAGEN_SUBIR,
  VENTAS_CIERRES_VER: PERMISSION_VALUES.VENTAS_CAJAS_MODULO_VER,

  PERSONAS_VER: PERMISSION_VALUES.PERSONAS_MODULO_VER,
  PERSONAS_FILTROS_USAR: PERMISSION_VALUES.PERSONAS_USAR_FILTROS,
  EMPRESAS_VER: PERMISSION_VALUES.EMPRESAS_MODULO_VER,
  EMPRESAS_FILTROS_USAR: PERMISSION_VALUES.EMPRESAS_USAR_FILTROS,
  CLIENTES_VER: PERMISSION_VALUES.CLIENTES_MODULO_VER,
  CLIENTES_FILTROS_USAR: PERMISSION_VALUES.CLIENTES_USAR_FILTROS,
  EMPLEADOS_VER: PERMISSION_VALUES.EMPLEADOS_MODULO_VER,
  EMPLEADOS_FILTROS_USAR: PERMISSION_VALUES.EMPLEADOS_USAR_FILTROS,
  USUARIOS_VER: PERMISSION_VALUES.USUARIOS_MODULO_VER,
  USUARIOS_FILTROS_USAR: PERMISSION_VALUES.USUARIOS_USAR_FILTROS,
  ROLES_PERMISOS_VER: PERMISSION_VALUES.ROLES_PERMISOS_MODULO_VER,
  ROLES_PERMISOS_DETALLE_VER: PERMISSION_VALUES.ROLES_PERMISOS_ROLES_DETALLE_VER,
  ROLES_PERMISOS_BUSCAR: PERMISSION_VALUES.ROLES_PERMISOS_ROLES_BUSCAR
});

const normalizePermission = (permiso) => {
  const normalized = String(permiso ?? '').trim().toUpperCase();
  if (!normalized) return '';
  return PERMISSION_ALIASES[normalized] || normalized;
};

export const normalizePermissions = (permisos) =>
  uniquePermissions((Array.isArray(permisos) ? permisos : []).map(normalizePermission));

export const buildPermissionSet = (permisos) => new Set(normalizePermissions(permisos));

export const normalizeRoleName = (rol) =>
  String(rol ?? '')
    .trim()
    .replace(/[\s-]+/g, '_')
    .toUpperCase();

export const normalizeRoles = (roles) =>
  uniquePermissions((Array.isArray(roles) ? roles : []).map(normalizeRoleName));

export const isSuperAdminRole = (rol) => normalizeRoleName(rol) === 'SUPER_ADMIN';

export const isSuperAdminRoleList = (roles) => normalizeRoles(roles).some(isSuperAdminRole);

export const hasPermission = (permissionSet, permiso, options = {}) => {
  if (options?.isSuperAdmin) return true;

  const normalized = normalizePermission(permiso);
  if (!normalized) return false;
  if (!(permissionSet instanceof Set)) return false;
  return permissionSet.has(normalized);
};

export const hasAnyPermission = (permissionSet, permisosRequeridos, options = {}) => {
  if (options?.isSuperAdmin) return true;
  const required = normalizePermissions(permisosRequeridos);
  if (required.length === 0) return true;
  return required.some((permiso) => hasPermission(permissionSet, permiso));
};

export const hasAllPermissions = (permissionSet, permisosRequeridos, options = {}) => {
  if (options?.isSuperAdmin) return true;
  const required = normalizePermissions(permisosRequeridos);
  if (required.length === 0) return true;
  return required.every((permiso) => hasPermission(permissionSet, permiso));
};

const INVENTARIO_TAB_PERMISSIONS_MAP = Object.freeze({
  categorias: uniquePermissions([
    PERMISSIONS.INVENTARIO_CATEGORIAS_VER,
    PERMISSIONS.INVENTARIO_CATEGORIAS_CREAR,
    PERMISSIONS.INVENTARIO_CATEGORIAS_EDITAR,
    PERMISSIONS.INVENTARIO_CATEGORIAS_ELIMINAR,
    PERMISSIONS.INVENTARIO_CATEGORIAS_ESTADO_CAMBIAR,
    PERMISSIONS.INVENTARIO_CATEGORIAS_INSUMOS_VER,
    PERMISSIONS.INVENTARIO_CATEGORIAS_INSUMOS_CREAR,
    PERMISSIONS.INVENTARIO_CATEGORIAS_INSUMOS_EDITAR,
    PERMISSIONS.INVENTARIO_CATEGORIAS_INSUMOS_ELIMINAR,
    PERMISSIONS.INVENTARIO_CATEGORIAS_INSUMOS_ESTADO_CAMBIAR
  ]),
  insumos: uniquePermissions([
    PERMISSIONS.INVENTARIO_INSUMOS_VER,
    PERMISSIONS.INVENTARIO_INSUMOS_DETALLE_VER,
    PERMISSIONS.INVENTARIO_INSUMOS_CREAR,
    PERMISSIONS.INVENTARIO_INSUMOS_EDITAR,
    PERMISSIONS.INVENTARIO_INSUMOS_ELIMINAR,
    PERMISSIONS.INVENTARIO_INSUMOS_ESTADO_CAMBIAR,
    PERMISSIONS.INVENTARIO_ARCHIVOS_VER,
    PERMISSIONS.INVENTARIO_ARCHIVOS_SUBIR,
    PERMISSIONS.INVENTARIO_ARCHIVOS_ELIMINAR
  ]),
  productos: uniquePermissions([
    PERMISSIONS.INVENTARIO_PRODUCTOS_VER,
    PERMISSIONS.INVENTARIO_PRODUCTOS_CREAR,
    PERMISSIONS.INVENTARIO_PRODUCTOS_EDITAR,
    PERMISSIONS.INVENTARIO_PRODUCTOS_ELIMINAR,
    PERMISSIONS.INVENTARIO_PRODUCTOS_DETALLE_VER,
    PERMISSIONS.INVENTARIO_PRODUCTOS_ESTADO_CAMBIAR,
    PERMISSIONS.INVENTARIO_PRODUCTOS_IMAGEN_SUBIR,
    PERMISSIONS.INVENTARIO_PRODUCTOS_IMAGEN_ELIMINAR
  ]),
  almacenes: uniquePermissions([
    PERMISSIONS.INVENTARIO_ALMACENES_VER,
    PERMISSIONS.INVENTARIO_ALMACENES_DETALLE_VER,
    PERMISSIONS.INVENTARIO_PROVEEDORES_VER,
    PERMISSIONS.INVENTARIO_PROVEEDORES_DETALLE_VER,
    PERMISSIONS.INVENTARIO_MOVIMIENTOS_VER,
    PERMISSIONS.INVENTARIO_ALMACENES_CREAR,
    PERMISSIONS.INVENTARIO_ALMACENES_EDITAR,
    PERMISSIONS.INVENTARIO_ALMACENES_ELIMINAR,
    PERMISSIONS.INVENTARIO_ALMACENES_ESTADO_CAMBIAR,
    PERMISSIONS.INVENTARIO_PROVEEDORES_CREAR,
    PERMISSIONS.INVENTARIO_PROVEEDORES_EDITAR,
    PERMISSIONS.INVENTARIO_PROVEEDORES_ELIMINAR,
    PERMISSIONS.INVENTARIO_PROVEEDORES_ESTADO_CAMBIAR,
    PERMISSIONS.INVENTARIO_MOVIMIENTOS_CREAR,
    PERMISSIONS.INVENTARIO_MOVIMIENTOS_EDITAR,
    PERMISSIONS.INVENTARIO_MOVIMIENTOS_ELIMINAR
  ]),
  alertas: uniquePermissions([
    PERMISSIONS.INVENTARIO_ALERTAS_VER,
    PERMISSIONS.INVENTARIO_ALERTAS_ACTUALIZAR,
    PERMISSIONS.INVENTARIO_ALERTAS_STOCK_MINIMO_EDITAR
  ]),
  // AM: tab de ordenes de compra dentro de Inventario.
  ordenes_compra: uniquePermissions([
    PERMISSIONS.INVENTARIO_OC_VER_FLUJO,
    PERMISSIONS.INVENTARIO_OC_VER_DETALLE,
    PERMISSIONS.INVENTARIO_OC_CREAR_SOLICITUD,
    PERMISSIONS.INVENTARIO_OC_EDITAR_SOLICITUD,
    PERMISSIONS.INVENTARIO_OC_APROBAR,
    PERMISSIONS.INVENTARIO_OC_RECHAZAR,
    PERMISSIONS.INVENTARIO_OC_CANCELAR,
    PERMISSIONS.INVENTARIO_OC_RECEPCIONAR,
    PERMISSIONS.INVENTARIO_OC_CONVERTIR_CONTINUAR,
    PERMISSIONS.INVENTARIO_OC_ABASTECER,
    PERMISSIONS.INVENTARIO_OC_SUBIR_FACTURA,
    PERMISSIONS.INVENTARIO_OC_SUBIR_DEPOSITO,
    PERMISSIONS.INVENTARIO_OC_VER_EVIDENCIAS,
    PERMISSIONS.INVENTARIO_OC_VER_HISTORIAL,
    PERMISSIONS.INVENTARIO_OC_CAMBIAR_ESTADO,
    PERMISSIONS.INVENTARIO_OC_REVISAR_SOLICITUD_ITEM,
    PERMISSIONS.INVENTARIO_OC_ATENDER_SOLICITUD_ITEM,
    PERMISSIONS.INVENTARIO_ORDENES_COMPRA_VER,
    PERMISSIONS.INVENTARIO_ORDENES_COMPRA_CREAR,
    PERMISSIONS.INVENTARIO_ORDENES_COMPRA_VER_TODAS,
    PERMISSIONS.INVENTARIO_ORDENES_COMPRA_GESTIONAR,
    PERMISSIONS.INVENTARIO_ORDENES_COMPRA_CONVERTIR,
    PERMISSIONS.INVENTARIO_ORDENES_COMPRA_ABASTECER,
    PERMISSIONS.INVENTARIO_ORDENES_COMPRA_RECEPCIONAR
  ]),
  // AM: tab visual del nuevo submodulo de mobiliario en inventario.
  mobiliario: uniquePermissions([
    PERMISSIONS.INVENTARIO_MOBILIARIO_VER,
    PERMISSIONS.INVENTARIO_MOBILIARIO_DETALLE_VER,
    PERMISSIONS.INVENTARIO_MOBILIARIO_CREAR,
    PERMISSIONS.INVENTARIO_MOBILIARIO_EDITAR,
    PERMISSIONS.INVENTARIO_MOBILIARIO_ESTADO_CAMBIAR
  ])
});

const PERSONAS_TAB_PERMISSIONS_MAP = Object.freeze({
  personas: uniquePermissions([
    PERMISSIONS.PERSONAS_MODULO_VER
  ]),
  empresas: uniquePermissions([
    PERMISSIONS.EMPRESAS_MODULO_VER
  ]),
  clientes: uniquePermissions([
    PERMISSIONS.CLIENTES_MODULO_VER
  ]),
  empleados: uniquePermissions([
    PERMISSIONS.EMPLEADOS_MODULO_VER
  ]),
  planillas: uniquePermissions([
    PERMISSIONS.PLANILLAS_MODULO_VER
  ]),
  usuarios: uniquePermissions([
    PERMISSIONS.USUARIOS_MODULO_VER
  ]),
  roles: uniquePermissions([
    PERMISSIONS.ROLES_PERMISOS_MODULO_VER
  ])
});

const PLANILLAS_MODULE_PERMISSIONS = uniquePermissions([
  PERMISSIONS.PLANILLAS_MODULO_VER,
  PERMISSIONS.PLANILLAS_LISTADO_VER,
  PERMISSIONS.PLANILLAS_DETALLE_VER,
  PERMISSIONS.PLANILLAS_GENERAR,
  PERMISSIONS.PLANILLAS_RECALCULAR,
  PERMISSIONS.PLANILLAS_ADELANTOS_APLICAR,
  PERMISSIONS.PLANILLAS_MOVIMIENTO_REGISTRAR,
  PERMISSIONS.PLANILLAS_MOVIMIENTO_ANULAR,
  PERMISSIONS.PLANILLAS_CERRAR,
  PERMISSIONS.PLANILLAS_PAGAR,
  PERMISSIONS.PLANILLAS_ANULAR,
  PERMISSIONS.PLANILLAS_AUDITORIA_VER
]);

const PLANILLAS_NAV_TAB_PERMISSIONS_MAP = Object.freeze({
  [PLANILLAS_NAV_TAB_KEYS.pagoPlanilla]: uniquePermissions([
    PERMISSIONS.PLANILLAS_MODULO_VER,
    PERMISSIONS.PLANILLAS_LISTADO_VER,
    PERMISSIONS.PLANILLAS_DETALLE_VER,
    PERMISSIONS.PLANILLAS_GENERAR,
    PERMISSIONS.PLANILLAS_RECALCULAR,
    PERMISSIONS.PLANILLAS_CERRAR,
    PERMISSIONS.PLANILLAS_PAGAR,
    PERMISSIONS.PLANILLAS_ANULAR
  ]),
  [PLANILLAS_NAV_TAB_KEYS.horasExtras]: uniquePermissions([
    PERMISSIONS.PLANILLAS_MODULO_VER,
    PERMISSIONS.PLANILLAS_DETALLE_VER,
    PERMISSIONS.PLANILLAS_RECALCULAR,
    PERMISSIONS.PLANILLAS_MOVIMIENTO_REGISTRAR
  ]),
  [PLANILLAS_NAV_TAB_KEYS.adelantosSalario]: uniquePermissions([
    PERMISSIONS.PLANILLAS_MODULO_VER,
    PERMISSIONS.PLANILLAS_DETALLE_VER,
    PERMISSIONS.PLANILLAS_ADELANTOS_APLICAR
  ]),
  [PLANILLAS_NAV_TAB_KEYS.bonosDeducciones]: uniquePermissions([
    PERMISSIONS.PLANILLAS_MODULO_VER,
    PERMISSIONS.PLANILLAS_DETALLE_VER,
    PERMISSIONS.PLANILLAS_MOVIMIENTO_REGISTRAR,
    PERMISSIONS.PLANILLAS_MOVIMIENTO_ANULAR
  ])
});

const SEGURIDAD_TAB_PERMISSIONS_MAP = Object.freeze({
  sesiones: uniquePermissions([
    PERMISSIONS.SEGURIDAD_VER,
    PERMISSIONS.SEGURIDAD_SESIONES_VER,
    PERMISSIONS.SEGURIDAD_SESIONES_VER_GLOBAL,
    PERMISSIONS.SEGURIDAD_SESIONES_CERRAR,
    PERMISSIONS.SEGURIDAD_SESIONES_CERRAR_OTRAS,
    PERMISSIONS.SEGURIDAD_SESIONES_CERRAR_GLOBAL,
    PERMISSIONS.SEGURIDAD_SESIONES_CERRAR_GLOBAL_MENOS_ACTUAL
  ]),
  usuarios: uniquePermissions([
    PERMISSIONS.SEGURIDAD_USUARIOS_VER,
    PERMISSIONS.SEGURIDAD_USUARIOS_AUDITORIA_VER,
    PERMISSIONS.SEGURIDAD_USUARIOS_AUDITORIA_SESIONES_VER,
    PERMISSIONS.SEGURIDAD_USUARIOS_AUDITORIA_LOGINS_VER,
    PERMISSIONS.SEGURIDAD_USUARIOS_SESIONES_CERRAR
  ]),
  password: uniquePermissions([
    PERMISSIONS.SEGURIDAD_VER,
    PERMISSIONS.SEGURIDAD_CONFIG_VER,
    PERMISSIONS.SEGURIDAD_CONFIG_EDITAR
  ]),
  logins: uniquePermissions([
    PERMISSIONS.SEGURIDAD_VER,
    PERMISSIONS.SEGURIDAD_LOGINS_VER
  ]),
  bitacoras: uniquePermissions([
    PERMISSIONS.SEGURIDAD_SESIONES_VER_GLOBAL,
    PERMISSIONS.SEGURIDAD_USUARIOS_AUDITORIA_VER
  ]),
  dashboard: uniquePermissions([
    PERMISSIONS.SEGURIDAD_SESIONES_VER_GLOBAL,
    PERMISSIONS.SEGURIDAD_USUARIOS_AUDITORIA_VER
  ])
});

const VENTAS_TAB_PERMISSIONS_MAP = Object.freeze({
  ventas: uniquePermissions([
    PERMISSIONS.VENTAS_VER,
    PERMISSIONS.VENTAS_DETALLE_VER,
    PERMISSIONS.VENTAS_EXPORTAR,
    PERMISSIONS.VENTAS_IMPRIMIR
  ]),
  caja: uniquePermissions([
    PERMISSIONS.VENTAS_CREAR,
    PERMISSIONS.VENTAS_CARRITO_EDITAR,
    PERMISSIONS.VENTAS_DESCUENTO_APLICAR,
    PERMISSIONS.VENTAS_METODO_PAGO_SELECCIONAR
  ]),
  pedidos: uniquePermissions([
    PERMISSIONS.VENTAS_VER,
    PERMISSIONS.VENTAS_DETALLE_VER
  ]),
  descuentos: uniquePermissions([
    PERMISSIONS.VENTAS_DESCUENTOS_CATALOGO_VER,
    PERMISSIONS.VENTAS_DESCUENTOS_CATALOGO_CREAR,
    PERMISSIONS.VENTAS_DESCUENTOS_CATALOGO_EDITAR,
    PERMISSIONS.VENTAS_DESCUENTOS_CATALOGO_ESTADO_CAMBIAR
  ])
});

const CIERRES_CAJA_TAB_PERMISSIONS_MAP = Object.freeze({
  operacion: uniquePermissions([
    PERMISSIONS.VENTAS_CIERRES_VER,
    PERMISSIONS.VENTAS_CIERRES_GESTIONAR,
    PERMISSIONS.VENTAS_CAJAS_MODULO_VER,
    PERMISSIONS.VENTAS_CAJAS_LISTADO_VER,
    PERMISSIONS.VENTAS_CAJAS_DETALLE_VER,
    PERMISSIONS.VENTAS_CAJAS_SESION_ABRIR,
    PERMISSIONS.VENTAS_CAJAS_SESION_CERRAR,
    PERMISSIONS.VENTAS_CAJAS_PARTICIPANTES_GESTIONAR,
    PERMISSIONS.VENTAS_CAJAS_ARQUEO_REGISTRAR,
    PERMISSIONS.VENTAS_CAJAS_MOVIMIENTO_MANUAL_REGISTRAR,
    PERMISSIONS.VENTAS_CAJAS_INCIDENCIA_GESTIONAR,
    PERMISSIONS.VENTAS_CAJAS_REPORTE_VER,
    PERMISSIONS.VENTAS_CAJAS_MULTISUCURSAL_VER,
    PERMISSIONS.VENTAS_CAJAS_DIFERENCIA_RESOLVER
  ]),
  'cierres-historial': uniquePermissions([
    PERMISSIONS.VENTAS_CIERRES_VER,
    PERMISSIONS.VENTAS_CAJAS_MODULO_VER,
    PERMISSIONS.VENTAS_CAJAS_LISTADO_VER,
    PERMISSIONS.VENTAS_CAJAS_DETALLE_VER,
    PERMISSIONS.VENTAS_CAJAS_REPORTE_VER,
    PERMISSIONS.VENTAS_CAJAS_MULTISUCURSAL_VER,
    PERMISSIONS.VENTAS_CAJAS_DIFERENCIA_RESOLVER
  ]),
  asignaciones: uniquePermissions([
    PERMISSIONS.VENTAS_CIERRES_VER,
    PERMISSIONS.VENTAS_CIERRES_GESTIONAR,
    PERMISSIONS.VENTAS_CAJAS_MODULO_VER,
    PERMISSIONS.VENTAS_CAJAS_LISTADO_VER,
    PERMISSIONS.VENTAS_CAJAS_DETALLE_VER,
    PERMISSIONS.VENTAS_CAJAS_PARTICIPANTES_GESTIONAR,
    PERMISSIONS.VENTAS_CAJAS_REPORTE_VER,
    PERMISSIONS.VENTAS_CAJAS_MULTISUCURSAL_VER
  ])
});

const MENU_TAB_BASE_PERMISSIONS = uniquePermissions([
  PERMISSIONS.MENU_VER,
  PERMISSIONS.MENU_PEDIDO_AGREGAR_ITEM,
  PERMISSIONS.MENU_PRODUCTO_DETALLE_VER,
  PERMISSIONS.MENU_PEDIDO_EDITAR_CANTIDAD,
  PERMISSIONS.MENU_PEDIDO_ELIMINAR_ITEM,
  PERMISSIONS.MENU_PEDIDO_CONFIRMAR
]);

const MENU_TAB_PERMISSIONS_MAP = Object.freeze({
  recetas: MENU_TAB_BASE_PERMISSIONS,
  extras: MENU_TAB_BASE_PERMISSIONS,
  combos: MENU_TAB_BASE_PERMISSIONS,
  salsas: MENU_TAB_BASE_PERMISSIONS,
  publicacion: MENU_TAB_BASE_PERMISSIONS,
  carrusel: MENU_TAB_BASE_PERMISSIONS,
  'vista-previa': MENU_TAB_BASE_PERMISSIONS
});

const FIDELIZACION_TAB_PERMISSIONS_MAP = Object.freeze({
  panel: uniquePermissions([
    PERMISSIONS.FIDELIZACION_VER_PANEL,
    PERMISSIONS.FIDELIZACION_VER_CLIENTES,
    PERMISSIONS.FIDELIZACION_VER_MOVIMIENTOS,
    PERMISSIONS.FIDELIZACION_CANJEAR_PRESENCIAL,
    PERMISSIONS.FIDELIZACION_VER_MULTISUCURSAL
  ]),
  canjes: uniquePermissions([
    PERMISSIONS.FIDELIZACION_VER_CANJES
  ])
});

const MODULE_ROUTE_PERMISSIONS = Object.freeze({
  dashboard: uniquePermissions([PERMISSIONS.DASHBOARD_VER]),
  personas: uniquePermissions(Object.values(PERSONAS_TAB_PERMISSIONS_MAP).flat()),
  planillas: PLANILLAS_MODULE_PERMISSIONS,
  sucursales: uniquePermissions([
    PERMISSIONS.SUCURSALES_VER,
    PERMISSIONS.SUCURSALES_CREAR,
    PERMISSIONS.SUCURSALES_EDITAR,
    PERMISSIONS.SUCURSALES_ELIMINAR,
    PERMISSIONS.SUCURSALES_ESTADO_CAMBIAR
  ]),
  inventario: uniquePermissions([
    PERMISSIONS.INVENTARIO_VER,
    ...Object.values(INVENTARIO_TAB_PERMISSIONS_MAP).flat()
  ]),
  ventas: uniquePermissions([
    PERMISSIONS.VENTAS_VER,
    ...Object.values(VENTAS_TAB_PERMISSIONS_MAP).flat()
  ]),
  'cierres-caja': uniquePermissions([
    PERMISSIONS.VENTAS_CIERRES_VER,
    PERMISSIONS.VENTAS_CIERRES_GESTIONAR,
    PERMISSIONS.VENTAS_CAJAS_MODULO_VER,
    ...Object.values(CIERRES_CAJA_TAB_PERMISSIONS_MAP).flat()
  ]),
  cocina: uniquePermissions([
    PERMISSIONS.COCINA_VER,
    PERMISSIONS.COCINA_ACTUALIZAR_TABLERO,
    PERMISSIONS.COCINA_BUSCAR,
    PERMISSIONS.COCINA_DETALLE_VER,
    PERMISSIONS.COCINA_FILTRAR_SUCURSAL,
    PERMISSIONS.COCINA_PEDIDO_INICIAR,
    PERMISSIONS.COCINA_PEDIDO_MARCAR_LISTO,
    PERMISSIONS.COCINA_PEDIDO_ENTREGAR
  ]),
  menu: uniquePermissions(Object.values(MENU_TAB_PERMISSIONS_MAP).flat()),
  seguridad: uniquePermissions([
    PERMISSIONS.SEGURIDAD_VER,
    ...Object.values(SEGURIDAD_TAB_PERMISSIONS_MAP).flat()
  ]),
  planillas: uniquePermissions([
    PERMISSIONS.PLANILLAS_MODULO_VER,
    PERMISSIONS.PLANILLAS_LISTADO_VER,
    PERMISSIONS.PLANILLAS_DETALLE_VER,
    PERMISSIONS.PLANILLAS_GENERAR,
    PERMISSIONS.PLANILLAS_RECALCULAR
  ]),
  fidelizacion: uniquePermissions([
    PERMISSIONS.FIDELIZACION_VER_PANEL,
    ...Object.values(FIDELIZACION_TAB_PERMISSIONS_MAP).flat()
  ]),
  configuracion: uniquePermissions([PERMISSIONS.CONFIGURACION_VER]),
  fidelizacion: uniquePermissions([PERMISSIONS.DASHBOARD_VER]),
  configuracion: uniquePermissions([
    PERMISSIONS.CONFIGURACION_VER,
    PERMISSIONS.CONFIGURACION_EMAIL_CAMPAIGNS_VER,
    PERMISSIONS.CONFIGURACION_EMAIL_CAMPAIGNS_GESTIONAR
  ]),
  perfil: uniquePermissions([
    PERMISSIONS.PERFIL_VER,
    PERMISSIONS.PERFIL_EDITAR,
    PERMISSIONS.PERFIL_PASSWORD_CAMBIAR
  ])
});

export const ROUTE_PERMISSIONS = Object.freeze(MODULE_ROUTE_PERMISSIONS);

export const NAV_ITEM_PERMISSIONS = Object.freeze({
  '/dashboard': MODULE_ROUTE_PERMISSIONS.dashboard,
  '/dashboard/personas': MODULE_ROUTE_PERMISSIONS.personas,
  '/dashboard/personas?tab=planillas': MODULE_ROUTE_PERMISSIONS.planillas,
  '/dashboard/sucursales': MODULE_ROUTE_PERMISSIONS.sucursales,
  '/dashboard/inventario': MODULE_ROUTE_PERMISSIONS.inventario,
  '/dashboard/ventas': MODULE_ROUTE_PERMISSIONS.ventas,
  '/dashboard/cierres-caja': MODULE_ROUTE_PERMISSIONS['cierres-caja'],
  '/dashboard/cocina': MODULE_ROUTE_PERMISSIONS.cocina,
  '/dashboard/menu': MODULE_ROUTE_PERMISSIONS.menu,
  '/dashboard/seguridad': MODULE_ROUTE_PERMISSIONS.seguridad,
  '/dashboard/planillas': MODULE_ROUTE_PERMISSIONS.planillas,
  '/dashboard/fidelizacion': MODULE_ROUTE_PERMISSIONS.fidelizacion,
  '/dashboard/configuracion': MODULE_ROUTE_PERMISSIONS.configuracion,
  '/dashboard/perfil': MODULE_ROUTE_PERMISSIONS.perfil
});

export const INVENTARIO_TAB_PERMISSIONS = Object.freeze(INVENTARIO_TAB_PERMISSIONS_MAP);
export const PERSONAS_TAB_PERMISSIONS = Object.freeze(PERSONAS_TAB_PERMISSIONS_MAP);
export const SEGURIDAD_TAB_PERMISSIONS = Object.freeze(SEGURIDAD_TAB_PERMISSIONS_MAP);
export const VENTAS_TAB_PERMISSIONS = Object.freeze(VENTAS_TAB_PERMISSIONS_MAP);
export const CIERRES_CAJA_TAB_PERMISSIONS = Object.freeze(CIERRES_CAJA_TAB_PERMISSIONS_MAP);
export const MENU_TAB_PERMISSIONS = Object.freeze(MENU_TAB_PERMISSIONS_MAP);
export const FIDELIZACION_TAB_PERMISSIONS = Object.freeze(FIDELIZACION_TAB_PERMISSIONS_MAP);

export const MODULE_NAV_ITEMS = Object.freeze([
  { key: 'dashboard', name: 'Dashboard', path: '/dashboard', icon: 'bi-grid-1x2' },
  { key: 'sucursales', name: 'Sucursales', path: '/dashboard/sucursales', icon: 'bi-shop' },
  { key: 'personas', name: 'Personas/Empresas', path: '/dashboard/personas', icon: 'bi-people' },
  { key: 'planillas', name: 'Planillas', path: '/dashboard/planillas', icon: 'bi-cash-coin' },
  { key: 'inventario', name: 'Inventario', path: '/dashboard/inventario', icon: 'bi-box-seam' },
  { key: 'ventas', name: 'Ventas', path: '/dashboard/ventas', icon: 'bi-cart3' },
  { key: 'cierres-caja', name: 'Cierres de caja', path: '/dashboard/cierres-caja', icon: 'bi-safe' },
  { key: 'cocina', name: 'Cocina', path: '/dashboard/cocina', icon: 'bi-display' },
  { key: 'menu', name: 'Menu', path: '/dashboard/menu', icon: 'bi-journal-text' },
  { key: 'fidelizacion', name: 'Fidelizacion', path: '/dashboard/fidelizacion', icon: 'bi-star' },
  { key: 'seguridad', name: 'Seguridad', path: '/dashboard/seguridad', icon: 'bi-shield-lock' },
  { key: 'configuracion', name: 'Configuracion', path: '/dashboard/configuracion', icon: 'bi-gear' }
]);

export const MODULE_PRIMARY_PERMISSION = Object.freeze({
  dashboard: PERMISSIONS.DASHBOARD_VER,
  personas: PERMISSIONS.PERSONAS_MODULO_VER,
  planillas: PERMISSIONS.PLANILLAS_MODULO_VER,
  sucursales: PERMISSIONS.SUCURSALES_VER,
  inventario: PERMISSIONS.INVENTARIO_VER,
  ventas: PERMISSIONS.VENTAS_VER,
  'cierres-caja': PERMISSIONS.VENTAS_CAJAS_MODULO_VER,
  cocina: PERMISSIONS.COCINA_VER,
  menu: PERMISSIONS.MENU_VER,
  fidelizacion: PERMISSIONS.FIDELIZACION_VER_PANEL,
  seguridad: PERMISSIONS.SEGURIDAD_VER,
  configuracion: PERMISSIONS.CONFIGURACION_VER,
  perfil: PERMISSIONS.PERFIL_VER
});

export const MODULE_TAB_CONFIG = Object.freeze({
  inventario: [
    { key: 'categorias', label: 'Categorias', icon: 'bi bi-tag', required: INVENTARIO_TAB_PERMISSIONS_MAP.categorias },
    { key: 'insumos', label: 'Insumos', icon: 'bi bi-box-seam', required: INVENTARIO_TAB_PERMISSIONS_MAP.insumos },
    { key: 'productos', label: 'Productos', icon: 'bi bi-basket', required: INVENTARIO_TAB_PERMISSIONS_MAP.productos },
    { key: 'almacenes', label: 'Almacenes', icon: 'bi bi-building', required: INVENTARIO_TAB_PERMISSIONS_MAP.almacenes },
    // AM: acceso visual al submodulo de ordenes de compra.
    { key: 'ordenes_compra', label: 'Ordenes compra', icon: 'bi bi-bag-check', required: INVENTARIO_TAB_PERMISSIONS_MAP.ordenes_compra },
    // AM: acceso visual al submodulo de mobiliario.
    { key: 'mobiliario', label: 'Mobiliario', icon: 'bi bi-archive', required: INVENTARIO_TAB_PERMISSIONS_MAP.mobiliario }
  ],
  personas: [
    { key: 'personas', label: 'Personas', icon: 'bi bi-person', required: PERSONAS_TAB_PERMISSIONS_MAP.personas },
    { key: 'empresas', label: 'Empresas', icon: 'bi bi-building', required: PERSONAS_TAB_PERMISSIONS_MAP.empresas },
    { key: 'clientes', label: 'Clientes', icon: 'bi bi-people', required: PERSONAS_TAB_PERMISSIONS_MAP.clientes },
    { key: 'empleados', label: 'Empleados', icon: 'bi bi-briefcase', required: PERSONAS_TAB_PERMISSIONS_MAP.empleados },
    { key: 'usuarios', label: 'Usuarios', icon: 'bi bi-person-gear', required: PERSONAS_TAB_PERMISSIONS_MAP.usuarios },
    { key: 'roles', label: 'Roles y permisos', icon: 'bi bi-person-lock', required: PERSONAS_TAB_PERMISSIONS_MAP.roles }
  ],
  planillas: PLANILLAS_NAV_TABS.map((tab) => ({
    key: tab.key,
    label: tab.label,
    icon: tab.icon,
    required: PLANILLAS_NAV_TAB_PERMISSIONS_MAP[tab.key] || PLANILLAS_MODULE_PERMISSIONS
  })),
  seguridad: [
    { key: 'sesiones', label: 'Sesiones activas', icon: 'bi bi-laptop', required: SEGURIDAD_TAB_PERMISSIONS_MAP.sesiones },
    { key: 'usuarios', label: 'Usuarios', icon: 'bi bi-people', required: SEGURIDAD_TAB_PERMISSIONS_MAP.usuarios },
    { key: 'password', label: 'Politicas de contrasena', icon: 'bi bi-key', required: SEGURIDAD_TAB_PERMISSIONS_MAP.password },
    { key: 'logins', label: 'Logs de login', icon: 'bi bi-journal-text', required: SEGURIDAD_TAB_PERMISSIONS_MAP.logins },
    { key: 'bitacoras', label: 'Bitacoras', icon: 'bi bi-clipboard-data', required: SEGURIDAD_TAB_PERMISSIONS_MAP.bitacoras },
    {
      key: 'dashboard',
      label: 'Dashboard',
      icon: 'bi bi-graph-up-arrow',
      required: SEGURIDAD_TAB_PERMISSIONS_MAP.dashboard,
      superAdminOnly: true
    }
  ],
  ventas: [
    { key: 'ventas', label: 'Ventas', icon: 'bi bi-receipt-cutoff', required: VENTAS_TAB_PERMISSIONS_MAP.ventas },
    { key: 'caja', label: 'Caja', icon: 'bi bi-cart3', required: VENTAS_TAB_PERMISSIONS_MAP.caja },
    { key: 'pedidos', label: 'Pedidos', icon: 'bi bi-journal-richtext', required: VENTAS_TAB_PERMISSIONS_MAP.pedidos },
    { key: 'descuentos', label: 'Descuentos', icon: 'bi bi-tags', required: VENTAS_TAB_PERMISSIONS_MAP.descuentos }
  ],
  'cierres-caja': [
    { key: 'operacion', label: 'Operacion', icon: 'bi bi-safe2', required: CIERRES_CAJA_TAB_PERMISSIONS_MAP.operacion },
    { key: 'cierres-historial', label: 'Cierres e historial', icon: 'bi bi-clock-history', required: CIERRES_CAJA_TAB_PERMISSIONS_MAP['cierres-historial'] },
    { key: 'asignaciones', label: 'Asignaciones', icon: 'bi bi-people-fill', required: CIERRES_CAJA_TAB_PERMISSIONS_MAP.asignaciones }
  ],
  menu: [
    { key: 'recetas', label: 'Recetas', icon: 'bi bi-journal-richtext', required: MENU_TAB_PERMISSIONS_MAP.recetas },
    { key: 'extras', label: 'Extras', icon: 'bi bi-plus-square-dotted', required: MENU_TAB_PERMISSIONS_MAP.extras },
    { key: 'combos', label: 'Combos', icon: 'bi bi-collection', required: MENU_TAB_PERMISSIONS_MAP.combos },
    { key: 'salsas', label: 'Salsas', icon: 'bi bi-droplet', required: MENU_TAB_PERMISSIONS_MAP.salsas },
    { key: 'publicacion', label: 'Publicacion', icon: 'bi bi-cloud-upload', required: MENU_TAB_PERMISSIONS_MAP.publicacion },
    { key: 'carrusel', label: 'Carrusel', icon: 'bi bi-images', required: MENU_TAB_PERMISSIONS_MAP.carrusel },
    {
      key: 'vista-previa',
      label: 'Vista previa',
      icon: 'bi bi-eye',
      required: MENU_TAB_PERMISSIONS_MAP['vista-previa']
    }
  ],
  fidelizacion: [
    { key: 'panel', label: 'Resumen y Clientes', icon: 'bi bi-star', required: FIDELIZACION_TAB_PERMISSIONS_MAP.panel },
    { key: 'canjes', label: 'Canjes', icon: 'bi bi-gift', required: FIDELIZACION_TAB_PERMISSIONS_MAP.canjes }
  ]
});

const VENTAS_STATS_POLICY = Object.freeze({
  DEFAULT: ['totalVentas', 'totalFacturado', 'ticketPromedio', 'completadas', 'pendientes'],
  CAJERO: ['totalVentas', 'completadas', 'pendientes']
});

export const resolveVentasStatsVisibility = (roles, options = {}) => {
  if (options?.isSuperAdmin) return VENTAS_STATS_POLICY.DEFAULT;

  const roleSet = new Set(normalizeRoles(roles));
  if (roleSet.has('CAJERO')) {
    return VENTAS_STATS_POLICY.CAJERO;
  }

  return VENTAS_STATS_POLICY.DEFAULT;
};

export const isTabAllowed = (permissionSet, tabKey, map, options = {}) => {
  const required = map?.[tabKey] || [];
  return hasAnyPermission(permissionSet, required, options);
};

export const resolveFirstAllowedTab = (tabKeys, permissionSet, map, fallbackKey, options = {}) => {
  const keys = Array.isArray(tabKeys) ? tabKeys : [];
  const firstAllowed = keys.find((key) => isTabAllowed(permissionSet, key, map, options));
  return firstAllowed || fallbackKey || keys[0] || null;
};

export const getModulePermissions = (moduleKey) => MODULE_ROUTE_PERMISSIONS[moduleKey] || [];

export const canAccessModule = (permissionSet, moduleKey, options = {}) =>
  hasAnyPermission(permissionSet, getModulePermissions(moduleKey), options);

export const getVisibleModuleItems = (permissionSet, options = {}) =>
  MODULE_NAV_ITEMS.filter((item) => canAccessModule(permissionSet, item.key, options));

export const getAllowedTabs = (moduleKey, permissionSet, options = {}) =>
  (MODULE_TAB_CONFIG[moduleKey] || []).filter((tab) =>
    hasAnyPermission(permissionSet, tab.required || [], options)
    && (!tab.superAdminOnly || Boolean(options?.isSuperAdmin))
  );

export const getFirstAccessibleDashboardPath = (permissionSet, options = {}) => {
  const nextModule = MODULE_NAV_ITEMS.find(
    (item) => item.key !== 'dashboard' && canAccessModule(permissionSet, item.key, options)
  );

  if (nextModule) return nextModule.path;

  if (canAccessModule(permissionSet, 'perfil', options)) {
    return '/dashboard/perfil';
  }

  return null;
};
